apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: pjb-api-backend-tls
  namespace: pjb
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: pjb-api
      sectionName: http
  validation:
    wellKnownCACertificates: System
    hostname: pjb-api.pjb.svc.cluster.local
    subjectAltNames:
      - type: URI
        uri: spiffe://pjb.jus.br/pjb/workload/api
