apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod-sovereign-spiffe-trust-plane
  - gatewayclass.yaml
  - gateway.yaml
  - httproute-api.yaml
  - backendtlspolicy-api.yaml
