apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod-sovereign-operational-resilience-mesh
patches:
  - path: patch-configmap.yaml
  - path: patch-api-deployment.yaml
  - path: patch-worker-deployment.yaml
  - path: patch-api-scaledobject.yaml
  - path: patch-worker-scaledobject.yaml
