apiVersion: v1
kind: ConfigMap
metadata:
  name: pjb-backend-config
data:
  PJB_API_CRISIS_CONTROL_ENABLED: "true"
  PJB_API_CRISIS_CONTROL_MODE: "CONTAINMENT"
  PJB_API_CRISIS_CONTROL_DEBUG_HEADERS: "false"
  PJB_PROCESSUAL_READ_MODELS_RECOMPOSITION_POLL_MS: "120000"
  PJB_PROCESSUAL_READ_MODELS_RECOMPOSITION_BATCH_SIZE: "5"
  PJB_PROCESSUAL_READ_MODELS_RECOMPOSITION_MAX_ATTEMPTS: "3"
