package com.tcc.pjb.backend.core.processo.recursal.domain.foundation;

import java.util.List;

public final class RecursalFormalSectionLabels {

    public static final String PETICAO_INTERPOSICAO = "PETICAO_INTERPOSICAO";
    public static final String ENDERECAMENTO_A_QUO = "ENDERECAMENTO_A_QUO";
    public static final String ENDERECAMENTO_AD_QUEM = "ENDERECAMENTO_AD_QUEM";
    public static final String IDENTIFICACAO_PARTES_RECURSAIS = "IDENTIFICACAO_PARTES_RECURSAIS";
    public static final String SINTESE_PROCESSO = "SINTESE_PROCESSO";
    public static final String SUCUMBENCIA_RECIPROCA = "SUCUMBENCIA_RECIPROCA";
    public static final String SUBORDINACAO_RECURSO_PRINCIPAL = "SUBORDINACAO_RECURSO_PRINCIPAL";
    public static final String DECISAO_MONOCRATICA_RELATOR = "DECISAO_MONOCRATICA_RELATOR";
    public static final String CONFRONTO_ANALITICO_DIVERGENCIA = "CONFRONTO_ANALITICO_DIVERGENCIA";
    public static final String PEDIDO_SUSTENTACAO_ORAL = "PEDIDO_SUSTENTACAO_ORAL";
    public static final String PEDIDO_SANEAMENTO_VICIO_FORMAL = "PEDIDO_SANEAMENTO_VICIO_FORMAL";
    public static final String RAZOES_RECURSAIS = "RAZOES_RECURSAIS";
    public static final String CABIMENTO = "CABIMENTO";
    public static final String LEGITIMIDADE = "LEGITIMIDADE";
    public static final String INTERESSE_RECURSAL = "INTERESSE_RECURSAL";
    public static final String TEMPESTIVIDADE = "TEMPESTIVIDADE";
    public static final String PREPARO = "PREPARO";
    public static final String REGULARIDADE_FORMAL = "REGULARIDADE_FORMAL";
    public static final String CONTRARRAZOES = "CONTRARRAZOES";
    public static final String IMPUGNACAO_ESPECIFICA_RECURSO_PRINCIPAL = "IMPUGNACAO_ESPECIFICA_RECURSO_PRINCIPAL";
    public static final String PEDIDO_NAO_CONHECIMENTO = "PEDIDO_NAO_CONHECIMENTO";
    public static final String PEDIDO_NAO_PROVIMENTO = "PEDIDO_NAO_PROVIMENTO";
    public static final String EFEITOS_RECURSAIS = "EFEITOS_RECURSAIS";
    public static final String PEDIDO_EFEITO_SUSPENSIVO = "PEDIDO_EFEITO_SUSPENSIVO";
    public static final String FUNDAMENTOS_EMBARGOS = "FUNDAMENTOS_EMBARGOS";
    public static final String PEDIDO_EFEITO_INFRINGENTE = "PEDIDO_EFEITO_INFRINGENTE";
    public static final String IMPUGNACAO_INADMISSIBILIDADE = "IMPUGNACAO_INADMISSIBILIDADE";
    public static final String DEMONSTRACAO_DIVERGENCIA = "DEMONSTRACAO_DIVERGENCIA";
    public static final String ACORDAO_PARADIGMA = "ACORDAO_PARADIGMA";
    public static final String RENUNCIA_DIREITO_RECORRER = "RENUNCIA_DIREITO_RECORRER";
    public static final String DESISTENCIA_RECURSO = "DESISTENCIA_RECURSO";
    public static final String AQUIESCENCIA_DECISAO = "AQUIESCENCIA_DECISAO";
    public static final String DISTRIBUICAO_TRIBUNAL = "DISTRIBUICAO_TRIBUNAL";
    public static final String RELATORIA = "RELATORIA";
    public static final String PAUTA_JULGAMENTO = "PAUTA_JULGAMENTO";
    public static final String SUSTENTACAO_ORAL = "SUSTENTACAO_ORAL";
    public static final String JULGAMENTO_COLEGIADO = "JULGAMENTO_COLEGIADO";
    public static final String PUBLICACAO_ACORDAO = "PUBLICACAO_ACORDAO";
    public static final String PAINEL_JURISDICIONAL_DESTINO = "PAINEL_JURISDICIONAL_DESTINO";
    public static final String ORGAO_JULGADOR_COMPETENTE = "ORGAO_JULGADOR_COMPETENTE";
    public static final String VINCULO_PROCESSO_ORIGEM = "VINCULO_PROCESSO_ORIGEM";
    public static final String VISIBILIDADE_ORIGEM = "VISIBILIDADE_ORIGEM";
    public static final String FILA_INTEGRACAO_ORGAO_PROLATOR = "FILA_INTEGRACAO_ORGAO_PROLATOR";
    public static final String COLEGIADO_RECURSAL_PROPRIO = "COLEGIADO_RECURSAL_PROPRIO";
    public static final String JUIZO_ADMISSIBILIDADE_TRIBUNAL_RECORRIDO = "JUIZO_ADMISSIBILIDADE_TRIBUNAL_RECORRIDO";
    public static final String SUBIDA_CORTE_SUPERIOR = "SUBIDA_CORTE_SUPERIOR";
    public static final String ESPELHO_SECRETARIA_MULTIGRAU = "ESPELHO_SECRETARIA_MULTIGRAU";
    public static final String CONTINUIDADE_OPERACIONAL_SECRETARIA = "CONTINUIDADE_OPERACIONAL_SECRETARIA";
    public static final String MESA_EXCECOES_SECRETARIA_DESTINO = "MESA_EXCECOES_SECRETARIA_DESTINO";
    public static final String COBERTURA_SUBSTITUICAO_SECRETARIA_DESTINO = "COBERTURA_SUBSTITUICAO_SECRETARIA_DESTINO";
    public static final String CATALOGO_FORMAL_SECRETARIA_DESTINO = "CATALOGO_FORMAL_SECRETARIA_DESTINO";
    public static final String SIMETRIA_SECRETARIA_INSTITUCIONAL = "SIMETRIA_SECRETARIA_INSTITUCIONAL";
    public static final String CAPACIDADES_NUCLEO_SECRETARIA_ORIGEM = "CAPACIDADES_NUCLEO_SECRETARIA_ORIGEM";
    public static final String CAPACIDADES_SECRETARIA_DESTINO_POR_GRAU = "CAPACIDADES_SECRETARIA_DESTINO_POR_GRAU";
    public static final String CAPACIDADES_SECRETARIA_INSTITUCIONAL_DESTINO = "CAPACIDADES_SECRETARIA_INSTITUCIONAL_DESTINO";
    public static final String CAPACIDADES_POS_JULGAMENTO_MULTIGRAU = "CAPACIDADES_POS_JULGAMENTO_MULTIGRAU";
    public static final String CAPACIDADES_PRESIDENCIA_VICE = "CAPACIDADES_PRESIDENCIA_VICE";
    public static final String CAPACIDADES_CORTE_SUPERIOR = "CAPACIDADES_CORTE_SUPERIOR";

    public static final String PAINEL_CIDADAO_PROCESSOS_PROPRIOS = "PAINEL_CIDADAO_PROCESSOS_PROPRIOS";
    public static final String FILTRO_ENVOLVIMENTO_CIDADAO = "FILTRO_ENVOLVIMENTO_CIDADAO";
    public static final String ULTIMAS_MOVIMENTACOES_RECURSAIS_CIDADAO = "ULTIMAS_MOVIMENTACOES_RECURSAIS_CIDADAO";
    public static final String CORES_PROCESSUAIS_RECURSAIS_CIDADAO = "CORES_PROCESSUAIS_RECURSAIS_CIDADAO";

    public static final String VISIBILIDADE_ESCALONADA_AUTOR_REU = "VISIBILIDADE_ESCALONADA_AUTOR_REU";
    public static final String PAINEL_RECURSAL_ADVOCACIA_FILTRADO = "PAINEL_RECURSAL_ADVOCACIA_FILTRADO";
    public static final String PAINEL_RECURSAL_DEFENSORIA_FILTRADO = "PAINEL_RECURSAL_DEFENSORIA_FILTRADO";
    public static final String PAINEL_RECURSAL_PROCURADORIA_FILTRADO = "PAINEL_RECURSAL_PROCURADORIA_FILTRADO";
    public static final String PAINEL_RECURSAL_MINISTERIO_PUBLICO_FILTRADO = "PAINEL_RECURSAL_MINISTERIO_PUBLICO_FILTRADO";
    public static final String FILTRO_RITO_RECURSO_EMBARGOS = "FILTRO_RITO_RECURSO_EMBARGOS";

    public static final String PRAZO_RECURSAL_REAL = "PRAZO_RECURSAL_REAL";
    public static final String CALENDARIO_RECURSAL_OPERACIONAL = "CALENDARIO_RECURSAL_OPERACIONAL";
    public static final String PAINEL_TEMPORAL_RECURSAL = "PAINEL_TEMPORAL_RECURSAL";
    public static final String PREVIEW_NOTIFICACOES_RECURSAIS = "PREVIEW_NOTIFICACOES_RECURSAIS";
    public static final String PREFERENCIAS_NOTIFICACAO_RECURSAL = "PREFERENCIAS_NOTIFICACAO_RECURSAL";
    public static final String INTIMACAO_MULTICANAL_RECURSAL = "INTIMACAO_MULTICANAL_RECURSAL";
    public static final String AVISOS_JANELA_CONTRARRAZOES_ADESIVO = "AVISOS_JANELA_CONTRARRAZOES_ADESIVO";
    public static final String AVISOS_PUBLICACAO_ACORDAO = "AVISOS_PUBLICACAO_ACORDAO";


    public static final String POS_JULGAMENTO_RECURSAL_ESCALONADO = "POS_JULGAMENTO_RECURSAL_ESCALONADO";
    public static final String MUDANCA_DEGRAU_PUBLICACAO_INTIMACAO = "MUDANCA_DEGRAU_PUBLICACAO_INTIMACAO";
    public static final String PUBLICACAO_REABERTURA_PRAZO = "PUBLICACAO_REABERTURA_PRAZO";
    public static final String TRANSITO_OU_NOVA_SUBIDA = "TRANSITO_OU_NOVA_SUBIDA";
    public static final String ALERTA_VERMELHO_PRAZO_CRITICO = "ALERTA_VERMELHO_PRAZO_CRITICO";
    public static final String ALERTA_MULTICANAL_TODOS_CANAIS = "ALERTA_MULTICANAL_TODOS_CANAIS";
    public static final String CORES_PROCESSUAIS_CRITICIDADE_RECURSAL = "CORES_PROCESSUAIS_CRITICIDADE_RECURSAL";
    public static final String VOTOS_VIVOS_RECURSAL = "VOTOS_VIVOS_RECURSAL";

    public static final String DEGRAUS_NOTIFICACAO_POR_PERFIL = "DEGRAUS_NOTIFICACAO_POR_PERFIL";
    public static final String CRITICIDADE_PRAZO_RECURSAL = "CRITICIDADE_PRAZO_RECURSAL";
    public static final String AVISOS_CIDADAO_PROCESSO_PROPRIO = "AVISOS_CIDADAO_PROCESSO_PROPRIO";
    public static final String AVISOS_REPRESENTACAO_TECNICA = "AVISOS_REPRESENTACAO_TECNICA";
    public static final String AVISOS_SECRETARIA_MAGISTRATURA = "AVISOS_SECRETARIA_MAGISTRATURA";




    public static final String REUSO_STUDIO_PETICIONAMENTO_PRIMEIRO_GRAU = "REUSO_STUDIO_PETICIONAMENTO_PRIMEIRO_GRAU";
    public static final String PERFIL_PETICAO_RECURSAL_ESPECIFICA = "PERFIL_PETICAO_RECURSAL_ESPECIFICA";
    public static final String PERFIL_PETICAO_EMBARGOS_ESPECIFICA = "PERFIL_PETICAO_EMBARGOS_ESPECIFICA";
    public static final String PERFIL_PARECER_MANIFESTACAO_INSTITUCIONAL = "PERFIL_PARECER_MANIFESTACAO_INSTITUCIONAL";
    public static final String MATRIZ_PECAS_RECURSAIS_POR_RAMO = "MATRIZ_PECAS_RECURSAIS_POR_RAMO";
    public static final String FILTRO_CAPACIDADE_POSTULATORIA_RECURSAL = "FILTRO_CAPACIDADE_POSTULATORIA_RECURSAL";
    public static final String CHECKLIST_DOSSIE_DOCUMENTAL_RECURSAL = "CHECKLIST_DOSSIE_DOCUMENTAL_RECURSAL";
    public static final String JORNADA_PROTOCOLO_RECURSAL_CLASSIFICADA = "JORNADA_PROTOCOLO_RECURSAL_CLASSIFICADA";

    public static final String MALOTES_E_ENCAMINHAMENTOS_RECURSAIS = "MALOTES_E_ENCAMINHAMENTOS_RECURSAIS";
    public static final String PETICIONAMENTO_RECURSO_EMBARGOS = "PETICIONAMENTO_RECURSO_EMBARGOS";
    public static final String ATOS_OPERACIONAIS_RECURSAIS = "ATOS_OPERACIONAIS_RECURSAIS";
    public static final String INTIMACOES_CITACOES_CHAMAMENTOS_RECURSAIS = "INTIMACOES_CITACOES_CHAMAMENTOS_RECURSAIS";
    public static final String AUXILIARES_JUSTICA_RECURSAL = "AUXILIARES_JUSTICA_RECURSAL";

    public static final String MALHA_RECURSAL_POR_RAMO = "MALHA_RECURSAL_POR_RAMO";
    public static final String FILTRO_RAMO_PROCESSUAL_DESTINO = "FILTRO_RAMO_PROCESSUAL_DESTINO";
    public static final String FILTRO_RITO_PROCESSUAL_DESTINO = "FILTRO_RITO_PROCESSUAL_DESTINO";
    public static final String SIGILO_GRADUADO_POR_RAMO = "SIGILO_GRADUADO_POR_RAMO";
    public static final String ESPELHO_MOVIMENTACOES_E_CORES_POR_RAMO = "ESPELHO_MOVIMENTACOES_E_CORES_POR_RAMO";

    public static final String VISIBILIDADE_ESCALONADA_PARTES = "VISIBILIDADE_ESCALONADA_PARTES";
    public static final String VISIBILIDADE_ESCALONADA_REPRESENTACAO_TECNICA = "VISIBILIDADE_ESCALONADA_REPRESENTACAO_TECNICA";
    public static final String VISIBILIDADE_ESCALONADA_APOIO_INSTITUCIONAL = "VISIBILIDADE_ESCALONADA_APOIO_INSTITUCIONAL";
    public static final String VISIBILIDADE_ESCALONADA_MAGISTRATURA_ORIGEM = "VISIBILIDADE_ESCALONADA_MAGISTRATURA_ORIGEM";
    public static final String VISIBILIDADE_ESCALONADA_MAGISTRATURA_DESTINO = "VISIBILIDADE_ESCALONADA_MAGISTRATURA_DESTINO";
    public static final String VISIBILIDADE_ESCALONADA_CORTE_SUPERIOR = "VISIBILIDADE_ESCALONADA_CORTE_SUPERIOR";
    public static final String PAINEL_MAGISTRADO_DESTINO = "PAINEL_MAGISTRADO_DESTINO";
    public static final String WORKBENCH_MAGISTRATURA_DESTINO = "WORKBENCH_MAGISTRATURA_DESTINO";
    public static final String WORKBENCH_DISTRIBUICAO_DESTINO = "WORKBENCH_DISTRIBUICAO_DESTINO";
    public static final String WORKBENCH_SECRETARIA_OPERACIONAL_DESTINO = "WORKBENCH_SECRETARIA_OPERACIONAL_DESTINO";
    public static final String WORKBENCH_INSTITUCIONAL_DESTINO = "WORKBENCH_INSTITUCIONAL_DESTINO";
    public static final String PAINEL_CORTE_SUPERIOR_DESTINO = "PAINEL_CORTE_SUPERIOR_DESTINO";
    public static final String VIOLACAO_LEI_FEDERAL = "VIOLACAO_LEI_FEDERAL";
    public static final String VIOLACAO_CONSTITUCIONAL = "VIOLACAO_CONSTITUCIONAL";
    public static final String PREQUESTIONAMENTO = "PREQUESTIONAMENTO";
    public static final String REPERCUSSAO_GERAL = "REPERCUSSAO_GERAL";

    public static final String MATRIZ_NACIONAL_RECURSOS_E_PECAS_POR_RITO = "MATRIZ_NACIONAL_RECURSOS_E_PECAS_POR_RITO";
    public static final String CIVIL_EXECUCAO_JUIZADOS_RECURSAIS = "CIVIL_EXECUCAO_JUIZADOS_RECURSAIS";
    public static final String PENAL_RECURSAL_E_EXECUCAO_PENAL = "PENAL_RECURSAL_E_EXECUCAO_PENAL";
    public static final String TRABALHISTA_RECURSAL_PROPRIO = "TRABALHISTA_RECURSAL_PROPRIO";
    public static final String ELEITORAL_RECURSAL_ESPECIALIDADE = "ELEITORAL_RECURSAL_ESPECIALIDADE";
    public static final String MILITAR_RECURSAL_PROPRIO = "MILITAR_RECURSAL_PROPRIO";
    public static final String PECAS_INSTITUCIONAIS_E_CONTRADITORIO_RECURSAL = "PECAS_INSTITUCIONAIS_E_CONTRADITORIO_RECURSAL";
    public static final String DIFERENCIACAO_ENDERECAMENTO_PRAZO_PREPARO_E_EFEITOS = "DIFERENCIACAO_ENDERECAMENTO_PRAZO_PREPARO_E_EFEITOS";
    public static final String MATRIZ_PECAS_CONCRETAS_POR_ATOR = "MATRIZ_PECAS_CONCRETAS_POR_ATOR";
    public static final String ADVOCACIA_PRIVADA_RECURSAL_CONTRARRAZOES_CONTRAMINUTA = "ADVOCACIA_PRIVADA_RECURSAL_CONTRARRAZOES_CONTRAMINUTA";
    public static final String DEFENSORIA_RECURSAL_DEFESA_HABEAS_CORPUS_CONTRARRAZOES = "DEFENSORIA_RECURSAL_DEFESA_HABEAS_CORPUS_CONTRARRAZOES";
    public static final String PROCURADORIA_RECURSAL_RECURSO_PARECER_CONTESTACAO = "PROCURADORIA_RECURSAL_RECURSO_PARECER_CONTESTACAO";
    public static final String MINISTERIO_PUBLICO_RECURSAL_MANIFESTACAO_PARECER_PROMOCAO = "MINISTERIO_PUBLICO_RECURSAL_MANIFESTACAO_PARECER_PROMOCAO";
    public static final String PECAS_COMPLEMENTARES_MEMORIAIS_QESITOS_RESPOSTA_LAUDO = "PECAS_COMPLEMENTARES_MEMORIAIS_QESITOS_RESPOSTA_LAUDO";
    public static final String CIVEL_JUIZADOS_PECAS_CONCRETAS = "CIVEL_JUIZADOS_PECAS_CONCRETAS";
    public static final String PENAL_PECAS_CONCRETAS = "PENAL_PECAS_CONCRETAS";
    public static final String TRABALHISTA_PECAS_CONCRETAS = "TRABALHISTA_PECAS_CONCRETAS";
    public static final String ELEITORAL_PECAS_CONCRETAS = "ELEITORAL_PECAS_CONCRETAS";
    public static final String MILITAR_PECAS_CONCRETAS = "MILITAR_PECAS_CONCRETAS";

    public static final String COMPORTAMENTO_RECURSAL_POR_TRIBUNAL_E_ORGAO = "COMPORTAMENTO_RECURSAL_POR_TRIBUNAL_E_ORGAO";
    public static final String MATRIZ_PRAZOS_POR_RITO_E_RECURSO = "MATRIZ_PRAZOS_POR_RITO_E_RECURSO";
    public static final String MATRIZ_PREPARO_DEPOSITO_E_CUSTAS = "MATRIZ_PREPARO_DEPOSITO_E_CUSTAS";
    public static final String FILTRO_TRIBUNAL_ORGAO_FRACIONARIO_COMPETENTE = "FILTRO_TRIBUNAL_ORGAO_FRACIONARIO_COMPETENTE";
    public static final String JUIZO_ADMISSIBILIDADE_E_FILTROS_ESPECIAIS = "JUIZO_ADMISSIBILIDADE_E_FILTROS_ESPECIAIS";
    public static final String REGRA_INTERRUPCAO_SUSPENSAO_E_REABERTURA_PRAZO = "REGRA_INTERRUPCAO_SUSPENSAO_E_REABERTURA_PRAZO";
    public static final String DIFERENCAS_CIVEL_JUIZADOS = "DIFERENCAS_CIVEL_JUIZADOS";
    public static final String DIFERENCAS_PENAL = "DIFERENCAS_PENAL";
    public static final String DIFERENCAS_TRABALHISTA = "DIFERENCAS_TRABALHISTA";
    public static final String DIFERENCAS_ELEITORAL = "DIFERENCAS_ELEITORAL";
    public static final String DIFERENCAS_MILITAR = "DIFERENCAS_MILITAR";
    public static final String COMUTACAO_CONTEXTUAL_POR_RITO_TRIBUNAL = "COMUTACAO_CONTEXTUAL_POR_RITO_TRIBUNAL";
    public static final String SHELL_CONTEXTUAL_RITO_TRIBUNAL = "SHELL_CONTEXTUAL_RITO_TRIBUNAL";
    public static final String VOCABULARIO_OPERACIONAL_CONTEXTUAL = "VOCABULARIO_OPERACIONAL_CONTEXTUAL";
    public static final String CARDS_PRIORIZADOS_CONTEXTO_ATIVO = "CARDS_PRIORIZADOS_CONTEXTO_ATIVO";
    public static final String ATALHOS_TATICOS_CONTEXTO_ATIVO = "ATALHOS_TATICOS_CONTEXTO_ATIVO";
    public static final String TELEMETRIA_E_FONTES_OFICIAIS_CONTEXTO_ATIVO = "TELEMETRIA_E_FONTES_OFICIAIS_CONTEXTO_ATIVO";
    public static final String MODO_DETALHE_RAMO_TRIBUNAL = "MODO_DETALHE_RAMO_TRIBUNAL";
    public static final String SILHUETA_VISUAL_SEM_RUIDO = "SILHUETA_VISUAL_SEM_RUIDO";
    public static final String MODO_PROCESSO_ATIVO_NO_PAINEL = "MODO_PROCESSO_ATIVO_NO_PAINEL";
    public static final String RETORNO_HOME_PADRAO_PJB = "RETORNO_HOME_PADRAO_PJB";
    public static final String CONTEXTO_CIDADAO_POR_RITO_TRIBUNAL = "CONTEXTO_CIDADAO_POR_RITO_TRIBUNAL";
    public static final String CONTEXTO_REPRESENTACAO_TECNICA_POR_RITO_TRIBUNAL = "CONTEXTO_REPRESENTACAO_TECNICA_POR_RITO_TRIBUNAL";
    public static final String CONTEXTO_SECRETARIA_POR_RITO_TRIBUNAL = "CONTEXTO_SECRETARIA_POR_RITO_TRIBUNAL";
    public static final String CONTEXTO_MAGISTRATURA_POR_RITO_TRIBUNAL = "CONTEXTO_MAGISTRATURA_POR_RITO_TRIBUNAL";
    public static final String CONTEXTO_INSTITUCIONAL_POR_RITO_TRIBUNAL = "CONTEXTO_INSTITUCIONAL_POR_RITO_TRIBUNAL";
    public static final String SHELL_CONTEXTUAL_POR_ATOR = "SHELL_CONTEXTUAL_POR_ATOR";
    public static final String PERFIL_ATUACAO_CONTEXTUAL = "PERFIL_ATUACAO_CONTEXTUAL";
    public static final String PROFILE_CODE_CONTEXTO_ATOR = "PROFILE_CODE_CONTEXTO_ATOR";
    public static final String CARDS_RISCO_POR_ATOR = "CARDS_RISCO_POR_ATOR";
    public static final String QUICK_ACTIONS_POR_ATOR = "QUICK_ACTIONS_POR_ATOR";
    public static final String LINGUAGEM_OPERACIONAL_POR_ATOR = "LINGUAGEM_OPERACIONAL_POR_ATOR";
    public static final String OBSERVABILIDADE_CONTEXTO_ATOR = "OBSERVABILIDADE_CONTEXTO_ATOR";

    public static final String POLITICA_VISUAL_OPERACIONAL_ATOR_RITO_TRIBUNAL = "POLITICA_VISUAL_OPERACIONAL_ATOR_RITO_TRIBUNAL";
    public static final String CRITICIDADE_VISUAL_E_SEMAFORO_CONTEXTUAL = "CRITICIDADE_VISUAL_E_SEMAFORO_CONTEXTUAL";
    public static final String VOCABULARIO_E_TOM_INSTITUCIONAL = "VOCABULARIO_E_TOM_INSTITUCIONAL";
    public static final String CARDS_E_ATALHOS_PRIMARIOS_CONTEXTO = "CARDS_E_ATALHOS_PRIMARIOS_CONTEXTO";
    public static final String DETALHE_EXPANDIVEL_E_DENSIDADE = "DETALHE_EXPANDIVEL_E_DENSIDADE";
    public static final String POLITICA_RETORNO_HOME_E_ISOLAMENTO_CONTEXTO = "POLITICA_RETORNO_HOME_E_ISOLAMENTO_CONTEXTO";


    public static final String TAXONOMIA_CNJ_CLASSES_ASSUNTOS_MOVIMENTOS = "TAXONOMIA_CNJ_CLASSES_ASSUNTOS_MOVIMENTOS";
    public static final String DE_PARA_EQUIVALENCIA_CLASSES = "DE_PARA_EQUIVALENCIA_CLASSES";
    public static final String TIPO_PETICAO_E_RITO_OPERACIONAL = "TIPO_PETICAO_E_RITO_OPERACIONAL";
    public static final String CLASSIFICACAO_PROCESSUAL_MAIS_ESPECIFICA = "CLASSIFICACAO_PROCESSUAL_MAIS_ESPECIFICA";
    public static final String COMPETENCIA_MULTIDIMENSIONAL_DISTRIBUICAO = "COMPETENCIA_MULTIDIMENSIONAL_DISTRIBUICAO";
    public static final String AMBIGUIDADE_COMPETENCIA_ESCOLHA_ASSISTIDA = "AMBIGUIDADE_COMPETENCIA_ESCOLHA_ASSISTIDA";
    public static final String DISTRIBUICAO_DEPENDENCIA_E_PROCESSO_REFERENCIA = "DISTRIBUICAO_DEPENDENCIA_E_PROCESSO_REFERENCIA";
    public static final String SIGILO_PRIORIDADES_ALERTAS_DISTRIBUICAO = "SIGILO_PRIORIDADES_ALERTAS_DISTRIBUICAO";
    public static final String PAINEL_EXTERNO_EXPEDIENTES_ACERVO_AGRUPADORES = "PAINEL_EXTERNO_EXPEDIENTES_ACERVO_AGRUPADORES";
    public static final String PAINEL_EXTERNO_CITACOES_INTIMACOES_AUDIENCIAS = "PAINEL_EXTERNO_CITACOES_INTIMACOES_AUDIENCIAS";
    public static final String PAINEL_EXTERNO_PENDENCIAS_SUBSTABELECIMENTO = "PAINEL_EXTERNO_PENDENCIAS_SUBSTABELECIMENTO";
    public static final String ESCRITORIO_ADVOCACIA_E_ASSISTENTES = "ESCRITORIO_ADVOCACIA_E_ASSISTENTES";
    public static final String REPRESENTANTE_PROCESSUAL_GESTOR_DISTRIBUIDOR_PADRAO = "REPRESENTANTE_PROCESSUAL_GESTOR_DISTRIBUIDOR_PADRAO";
    public static final String CAIXAS_ORGANIZACAO_FILTROS_HISTORICO = "CAIXAS_ORGANIZACAO_FILTROS_HISTORICO";
    public static final String PROCURADORIA_DEFENSORIA_ENTIDADES_E_VINCULOS = "PROCURADORIA_DEFENSORIA_ENTIDADES_E_VINCULOS";
    public static final String PRE_PAUTA_COBERTURA_E_DISTRIBUICAO_INSTITUCIONAL = "PRE_PAUTA_COBERTURA_E_DISTRIBUICAO_INSTITUCIONAL";

    public static final String PAINEL_ADVOGADO_CITACOES_INTIMACOES = "PAINEL_ADVOGADO_CITACOES_INTIMACOES";
    public static final String PAINEL_ADVOGADO_AUDIENCIAS_RECURSOS_SESSOES = "PAINEL_ADVOGADO_AUDIENCIAS_RECURSOS_SESSOES";
    public static final String PAINEL_ADVOGADO_PENDENCIAS_RELACAO_PROCESSOS = "PAINEL_ADVOGADO_PENDENCIAS_RELACAO_PROCESSOS";
    public static final String PAINEL_ADVOGADO_ATALHOS_CONFIGURACOES = "PAINEL_ADVOGADO_ATALHOS_CONFIGURACOES";
    public static final String PETICIONAMENTO_DISTRIBUICAO_FUTURA_E_LOTE = "PETICIONAMENTO_DISTRIBUICAO_FUTURA_E_LOTE";
    public static final String ASSINATURA_DIGITAL_EM_LOTE = "ASSINATURA_DIGITAL_EM_LOTE";
    public static final String PETICIONAMENTO_INTERMEDIARIO_EM_BLOCO = "PETICIONAMENTO_INTERMEDIARIO_EM_BLOCO";
    public static final String CONTROLE_DOCUMENTAL_PDF_E_ANEXOS = "CONTROLE_DOCUMENTAL_PDF_E_ANEXOS";
    public static final String CERTIDOES_NARRATORIA_E_EXECUTIVA = "CERTIDOES_NARRATORIA_E_EXECUTIVA";
    public static final String CERTIDOES_AUTENTICIDADE_E_DOWNLOAD = "CERTIDOES_AUTENTICIDADE_E_DOWNLOAD";
    public static final String CERTIDOES_TRANSITO_RETORNO_EXECUCAO = "CERTIDOES_TRANSITO_RETORNO_EXECUCAO";
    public static final String CAIXAS_RECURSAIS_ORGANIZACAO_E_FILTROS = "CAIXAS_RECURSAIS_ORGANIZACAO_E_FILTROS";
    public static final String HISTORICO_MOVIMENTACAO_DEVOLUCAO = "HISTORICO_MOVIMENTACAO_DEVOLUCAO";
    public static final String VINCULO_REPRESENTANTES_E_COBERTURA = "VINCULO_REPRESENTANTES_E_COBERTURA";
    public static final String WIZARD_DISTRIBUICAO_AI_5_ETAPAS = "WIZARD_DISTRIBUICAO_AI_5_ETAPAS";
    public static final String INFERENCIA_ASSUNTO_CLASSE_COMPETENCIA = "INFERENCIA_ASSUNTO_CLASSE_COMPETENCIA";
    public static final String PREFLIGHT_CANONICAL_ROUTING = "PREFLIGHT_CANONICAL_ROUTING";

    public static final String APLICACAO_CONTEXTO_RECURSAL_EMBARGOS = "APLICACAO_CONTEXTO_RECURSAL_EMBARGOS";
    public static final String FRONTEIRA_ENVOLVIMENTO_PROCESSO_ATIVO = "FRONTEIRA_ENVOLVIMENTO_PROCESSO_ATIVO";
    public static final String BUSCA_PROCESSUAL_NEUTRA_SEM_COMUTACAO = "BUSCA_PROCESSUAL_NEUTRA_SEM_COMUTACAO";
    public static final String SUPERFICIE_PUBLICA_EXISTENTE_PRESERVADA = "SUPERFICIE_PUBLICA_EXISTENTE_PRESERVADA";

    public static final String AUTOS_DIGITAIS_CAPA_E_LEMBRETES = "AUTOS_DIGITAIS_CAPA_E_LEMBRETES";
    public static final String AUTOS_DIGITAIS_ASSUNTOS_PARTES_EVENTOS = "AUTOS_DIGITAIS_ASSUNTOS_PARTES_EVENTOS";
    public static final String AUTOS_DIGITAIS_ACOES_E_INFORMACOES_ADICIONAIS = "AUTOS_DIGITAIS_ACOES_E_INFORMACOES_ADICIONAIS";
    public static final String HABILITACAO_ASSOCIACAO_PUBLICA_RECURSAL = "HABILITACAO_ASSOCIACAO_PUBLICA_RECURSAL";
    public static final String HABILITACAO_ASSOCIACAO_SIGILOSA_RECURSAL = "HABILITACAO_ASSOCIACAO_SIGILOSA_RECURSAL";
    public static final String HABILITACAO_ASSOCIACAO_FLUXO_AUDITAVEL = "HABILITACAO_ASSOCIACAO_FLUXO_AUDITAVEL";
    public static final String ESCRITORIO_RECURSAL_EQUIPES_ASSISTENTES = "ESCRITORIO_RECURSAL_EQUIPES_ASSISTENTES";
    public static final String SUBSTABELECIMENTO_RECURSAL_COM_E_SEM_RESERVA = "SUBSTABELECIMENTO_RECURSAL_COM_E_SEM_RESERVA";
    public static final String SUBSTABELECIMENTO_RECURSAL_CANCELAMENTO_AUDITAVEL = "SUBSTABELECIMENTO_RECURSAL_CANCELAMENTO_AUDITAVEL";
    public static final String COLABORACAO_MULTIMIDIA_VIDEOCONFERENCIA = "COLABORACAO_MULTIMIDIA_VIDEOCONFERENCIA";
    public static final String COLABORACAO_MULTIMIDIA_GRAVACAO_E_MIDIAS = "COLABORACAO_MULTIMIDIA_GRAVACAO_E_MIDIAS";
    public static final String COLABORACAO_MULTIMIDIA_VISUALIZADOR_E_AUTENTICIDADE = "COLABORACAO_MULTIMIDIA_VISUALIZADOR_E_AUTENTICIDADE";
    public static final String OBSERVABILIDADE_BI_RECUSAL = "OBSERVABILIDADE_BI_RECUSAL";
    public static final String OBSERVABILIDADE_INDEXACAO_E_RECUPERACAO = "OBSERVABILIDADE_INDEXACAO_E_RECUPERACAO";
    public static final String OBSERVABILIDADE_NOTIFICA_MOBILE_E_ALERTAS = "OBSERVABILIDADE_NOTIFICA_MOBILE_E_ALERTAS";

    private RecursalFormalSectionLabels() {
    }

    public static List<String> defaultOrder() {
        return List.of(
                PETICAO_INTERPOSICAO,
                ENDERECAMENTO_A_QUO,
                ENDERECAMENTO_AD_QUEM,
                IDENTIFICACAO_PARTES_RECURSAIS,
                RAZOES_RECURSAIS,
                SINTESE_PROCESSO,
                CABIMENTO,
                LEGITIMIDADE,
                INTERESSE_RECURSAL,
                TEMPESTIVIDADE,
                PREPARO,
                REGULARIDADE_FORMAL,
                CONTRARRAZOES,
                IMPUGNACAO_ESPECIFICA_RECURSO_PRINCIPAL,
                PEDIDO_NAO_CONHECIMENTO,
                PEDIDO_NAO_PROVIMENTO,
                EFEITOS_RECURSAIS,
                SUCUMBENCIA_RECIPROCA,
                SUBORDINACAO_RECURSO_PRINCIPAL,
                DECISAO_MONOCRATICA_RELATOR,
                PEDIDO_EFEITO_SUSPENSIVO,
                FUNDAMENTOS_EMBARGOS,
                PEDIDO_EFEITO_INFRINGENTE,
                IMPUGNACAO_INADMISSIBILIDADE,
                DEMONSTRACAO_DIVERGENCIA,
                ACORDAO_PARADIGMA,
                RENUNCIA_DIREITO_RECORRER,
                DESISTENCIA_RECURSO,
                AQUIESCENCIA_DECISAO,
                DISTRIBUICAO_TRIBUNAL,
                RELATORIA,
                PAUTA_JULGAMENTO,
                SUSTENTACAO_ORAL,
                JULGAMENTO_COLEGIADO,
                PUBLICACAO_ACORDAO,
                PAINEL_JURISDICIONAL_DESTINO,
                ORGAO_JULGADOR_COMPETENTE,
                VINCULO_PROCESSO_ORIGEM,
                VISIBILIDADE_ORIGEM,
                FILA_INTEGRACAO_ORGAO_PROLATOR,
                COLEGIADO_RECURSAL_PROPRIO,
                JUIZO_ADMISSIBILIDADE_TRIBUNAL_RECORRIDO,
                SUBIDA_CORTE_SUPERIOR,
                ESPELHO_SECRETARIA_MULTIGRAU,
                CONTINUIDADE_OPERACIONAL_SECRETARIA,
                MESA_EXCECOES_SECRETARIA_DESTINO,
                COBERTURA_SUBSTITUICAO_SECRETARIA_DESTINO,
                CATALOGO_FORMAL_SECRETARIA_DESTINO,
                SIMETRIA_SECRETARIA_INSTITUCIONAL,
                CAPACIDADES_NUCLEO_SECRETARIA_ORIGEM,
                CAPACIDADES_SECRETARIA_DESTINO_POR_GRAU,
                CAPACIDADES_SECRETARIA_INSTITUCIONAL_DESTINO,
                CAPACIDADES_POS_JULGAMENTO_MULTIGRAU,
                CAPACIDADES_PRESIDENCIA_VICE,
                CAPACIDADES_CORTE_SUPERIOR,
                PAINEL_CIDADAO_PROCESSOS_PROPRIOS,
                FILTRO_ENVOLVIMENTO_CIDADAO,
                ULTIMAS_MOVIMENTACOES_RECURSAIS_CIDADAO,
                CORES_PROCESSUAIS_RECURSAIS_CIDADAO,
                VISIBILIDADE_ESCALONADA_AUTOR_REU,
                PAINEL_RECURSAL_ADVOCACIA_FILTRADO,
                PAINEL_RECURSAL_DEFENSORIA_FILTRADO,
                PAINEL_RECURSAL_PROCURADORIA_FILTRADO,
                PAINEL_RECURSAL_MINISTERIO_PUBLICO_FILTRADO,
                FILTRO_RITO_RECURSO_EMBARGOS,
                PRAZO_RECURSAL_REAL,
                CALENDARIO_RECURSAL_OPERACIONAL,
                PAINEL_TEMPORAL_RECURSAL,
                PREVIEW_NOTIFICACOES_RECURSAIS,
                PREFERENCIAS_NOTIFICACAO_RECURSAL,
                INTIMACAO_MULTICANAL_RECURSAL,
                AVISOS_JANELA_CONTRARRAZOES_ADESIVO,
                AVISOS_PUBLICACAO_ACORDAO,
                POS_JULGAMENTO_RECURSAL_ESCALONADO,
                MUDANCA_DEGRAU_PUBLICACAO_INTIMACAO,
                PUBLICACAO_REABERTURA_PRAZO,
                TRANSITO_OU_NOVA_SUBIDA,
                ALERTA_VERMELHO_PRAZO_CRITICO,
                ALERTA_MULTICANAL_TODOS_CANAIS,
                CORES_PROCESSUAIS_CRITICIDADE_RECURSAL,
                VOTOS_VIVOS_RECURSAL,
                DEGRAUS_NOTIFICACAO_POR_PERFIL,
                REUSO_STUDIO_PETICIONAMENTO_PRIMEIRO_GRAU,
                PERFIL_PETICAO_RECURSAL_ESPECIFICA,
                PERFIL_PETICAO_EMBARGOS_ESPECIFICA,
                PERFIL_PARECER_MANIFESTACAO_INSTITUCIONAL,
                MATRIZ_PECAS_RECURSAIS_POR_RAMO,
                FILTRO_CAPACIDADE_POSTULATORIA_RECURSAL,
                CHECKLIST_DOSSIE_DOCUMENTAL_RECURSAL,
                JORNADA_PROTOCOLO_RECURSAL_CLASSIFICADA,
                CRITICIDADE_PRAZO_RECURSAL,
                AVISOS_CIDADAO_PROCESSO_PROPRIO,
                AVISOS_REPRESENTACAO_TECNICA,
                AVISOS_SECRETARIA_MAGISTRATURA,
                MALOTES_E_ENCAMINHAMENTOS_RECURSAIS,
                PETICIONAMENTO_RECURSO_EMBARGOS,
                ATOS_OPERACIONAIS_RECURSAIS,
                INTIMACOES_CITACOES_CHAMAMENTOS_RECURSAIS,
                AUXILIARES_JUSTICA_RECURSAL,
                MALHA_RECURSAL_POR_RAMO,
                FILTRO_RAMO_PROCESSUAL_DESTINO,
                FILTRO_RITO_PROCESSUAL_DESTINO,
                SIGILO_GRADUADO_POR_RAMO,
                ESPELHO_MOVIMENTACOES_E_CORES_POR_RAMO,
                MATRIZ_NACIONAL_RECURSOS_E_PECAS_POR_RITO,
                CIVIL_EXECUCAO_JUIZADOS_RECURSAIS,
                PENAL_RECURSAL_E_EXECUCAO_PENAL,
                TRABALHISTA_RECURSAL_PROPRIO,
                ELEITORAL_RECURSAL_ESPECIALIDADE,
                MILITAR_RECURSAL_PROPRIO,
                PECAS_INSTITUCIONAIS_E_CONTRADITORIO_RECURSAL,
                DIFERENCIACAO_ENDERECAMENTO_PRAZO_PREPARO_E_EFEITOS,
                MATRIZ_PECAS_CONCRETAS_POR_ATOR,
                ADVOCACIA_PRIVADA_RECURSAL_CONTRARRAZOES_CONTRAMINUTA,
                DEFENSORIA_RECURSAL_DEFESA_HABEAS_CORPUS_CONTRARRAZOES,
                PROCURADORIA_RECURSAL_RECURSO_PARECER_CONTESTACAO,
                MINISTERIO_PUBLICO_RECURSAL_MANIFESTACAO_PARECER_PROMOCAO,
                PECAS_COMPLEMENTARES_MEMORIAIS_QESITOS_RESPOSTA_LAUDO,
                CIVEL_JUIZADOS_PECAS_CONCRETAS,
                PENAL_PECAS_CONCRETAS,
                TRABALHISTA_PECAS_CONCRETAS,
                ELEITORAL_PECAS_CONCRETAS,
                MILITAR_PECAS_CONCRETAS,
                VISIBILIDADE_ESCALONADA_PARTES,
                VISIBILIDADE_ESCALONADA_REPRESENTACAO_TECNICA,
                VISIBILIDADE_ESCALONADA_APOIO_INSTITUCIONAL,
                VISIBILIDADE_ESCALONADA_MAGISTRATURA_ORIGEM,
                VISIBILIDADE_ESCALONADA_MAGISTRATURA_DESTINO,
                VISIBILIDADE_ESCALONADA_CORTE_SUPERIOR,
                PAINEL_MAGISTRADO_DESTINO,
                WORKBENCH_MAGISTRATURA_DESTINO,
                WORKBENCH_DISTRIBUICAO_DESTINO,
                WORKBENCH_SECRETARIA_OPERACIONAL_DESTINO,
                WORKBENCH_INSTITUCIONAL_DESTINO,
                PAINEL_CORTE_SUPERIOR_DESTINO,
                VIOLACAO_LEI_FEDERAL,
                VIOLACAO_CONSTITUCIONAL,
                PREQUESTIONAMENTO,
                REPERCUSSAO_GERAL,
                CONFRONTO_ANALITICO_DIVERGENCIA,
                PEDIDO_SUSTENTACAO_ORAL,
                PEDIDO_SANEAMENTO_VICIO_FORMAL
        );
    }
}
