package com.tcc.pjb.backend.core.processo.recursal.domain.foundation;

public final class RecursalNotificationLabels {

    public static final String SUITE_NOTIFICACIONAL_RECURSAL_GOVERNADA = "SUITE_NOTIFICACIONAL_RECURSAL_GOVERNADA";
    public static final String PREVIEW_MOBILE_PENDENCIAS_RECURSAIS = "PREVIEW_MOBILE_PENDENCIAS_RECURSAIS";
    public static final String GOVERNANCA_NOTIFICACIONAL_RECURSAL = "GOVERNANCA_NOTIFICACIONAL_RECURSAL";
    public static final String CIENCIA_NOTIFICACIONAL_RECURSAL = "CIENCIA_NOTIFICACIONAL_RECURSAL";

    public static final String PREFERENCIAS_FINAS_RECURSAIS = "PREFERENCIAS_FINAS_RECURSAIS";
    public static final String POLITICA_FEDERADA_NOTIFICACIONAL = "POLITICA_FEDERADA_NOTIFICACIONAL";
    public static final String ENTREGA_FEDERADA_SOBERANA = "ENTREGA_FEDERADA_SOBERANA";
    public static final String ENDURECIMENTO_MOBILE_EXTERNO_SOBERANO = "ENDURECIMENTO_MOBILE_EXTERNO_SOBERANO";
    public static final String POSTURA_MOBILE_SOBERANA = "POSTURA_MOBILE_SOBERANA";


    public static final String CANAL_PUSH_GOVERNADO = "PUSH_GOVERNADO";
    public static final String CANAL_INBOX_OPERACIONAL = "INBOX_OPERACIONAL";
    public static final String CANAL_CALENDARIO = "CALENDARIO";
    public static final String CANAL_MULTICANAL_PJB = "MULTICANAL_PJB";

    public static final String CANAL_EMAIL_GOVERNADO = "EMAIL_GOVERNADO";
    public static final String CANAL_SMS_GOVERNADO = "SMS_GOVERNADO";
    public static final String CANAL_PUSH_SOBERANO_EXTERNO = "PUSH_SOBERANO_EXTERNO";


    public static final String JANELA_CRITICIDADE_IMEDIATA = "JANELA_CRITICIDADE_IMEDIATA";
    public static final String JANELA_CRITICIDADE_TATICA = "JANELA_CRITICIDADE_TATICA";
    public static final String JANELA_CRITICIDADE_MONITORADA = "JANELA_CRITICIDADE_MONITORADA";

    public static final String AUDIENCIA_CIDADAO = "AUDIENCIA_CIDADAO";
    public static final String AUDIENCIA_REPRESENTACAO_TECNICA = "AUDIENCIA_REPRESENTACAO_TECNICA";
    public static final String AUDIENCIA_SECRETARIA_MAGISTRATURA = "AUDIENCIA_SECRETARIA_MAGISTRATURA";

    public static final String STATUS_CIENCIA_REGISTRADA = "CIENCIA_REGISTRADA";
    public static final String STATUS_CIENCIA_PENDENTE = "CIENCIA_PENDENTE";
    public static final String STATUS_SIGILO_REFORCADO = "SIGILO_REFORCADO";
    public static final String STATUS_FLUXO_GOVERNADO = "FLUXO_GOVERNADO";
    public static final String STATUS_POSTURA_APROVADA = "POSTURA_APROVADA";
    public static final String STATUS_POSTURA_RESTRITA = "POSTURA_RESTRITA";
    public static final String STATUS_POSTURA_BLOQUEADA = "POSTURA_BLOQUEADA";
    public static final String STATUS_ENTREGA_MOBILE_APROVADA = "ENTREGA_MOBILE_APROVADA";
    public static final String STATUS_ENTREGA_MOBILE_DEGRADADA = "ENTREGA_MOBILE_DEGRADADA";
    public static final String STATUS_ENTREGA_MOBILE_BLOQUEADA = "ENTREGA_MOBILE_BLOQUEADA";


    public static final String POLITICA_PERFIL_CIDADAO = "POLITICA_PERFIL_CIDADAO";
    public static final String POLITICA_PERFIL_REPRESENTACAO_TECNICA = "POLITICA_PERFIL_REPRESENTACAO_TECNICA";
    public static final String POLITICA_PERFIL_OPERACIONAL = "POLITICA_PERFIL_OPERACIONAL";
    public static final String POLITICA_FEDERADA_SOBERANA = "POLITICA_FEDERADA_SOBERANA";
    public static final String POLITICA_FEDERADA_INSTITUCIONAL = "POLITICA_FEDERADA_INSTITUCIONAL";
    public static final String POLITICA_ATESTACAO_APP_SOBERANO = "ATESTACAO_APP_SOBERANO";
    public static final String POLITICA_VINCULAR_TOKEN_AO_DISPOSITIVO = "VINCULAR_TOKEN_AO_DISPOSITIVO";
    public static final String POLITICA_ANTI_REPLAY_MOBILE = "ANTI_REPLAY_MOBILE";
    public static final String POLITICA_CRIPTOGRAFIA_PONTA_A_PONTA = "CRIPTOGRAFIA_PONTA_A_PONTA";
    public static final String POLITICA_RELAY_SOBERANO_ASSINADO = "RELAY_SOBERANO_ASSINADO";
    public static final String POLITICA_BIOMETRIA_LOCAL_GOVERNADA = "BIOMETRIA_LOCAL_GOVERNADA";


    public static final String POLITICA_SEM_SCHEDULER_PARALELO = "SEM_SCHEDULER_PARALELO";
    public static final String POLITICA_SEM_EXECUTOR_PARALELO = "SEM_EXECUTOR_PARALELO";
    public static final String POLITICA_REUSAR_PREFERENCIAS_GLOBAIS = "REUSAR_PREFERENCIAS_GLOBAIS";
    public static final String POLITICA_REUSAR_PREVIEW_CALENDARIO = "REUSAR_PREVIEW_CALENDARIO";
    public static final String POLITICA_REUSAR_CIENCIA_MULTICANAL = "REUSAR_CIENCIA_MULTICANAL";
    public static final String POLITICA_SIGILO_POR_PERFIL_E_PROCESSO = "SIGILO_POR_PERFIL_E_PROCESSO";

    public static final String POLITICA_REUSAR_PREFERENCIAS_POR_CANAL = "REUSAR_PREFERENCIAS_POR_CANAL";
    public static final String POLITICA_ENDURECER_ENTREGA_EXTERNA_SOBERANA = "ENDURECER_ENTREGA_EXTERNA_SOBERANA";
    public static final String POLITICA_FEDERAR_ENTREGA_INSTITUCIONAL = "FEDERAR_ENTREGA_INSTITUCIONAL";

    private RecursalNotificationLabels() {
    }
}
