package com.tcc.pjb.backend.ai.legalai.memory.domain;

public enum MemoryCandidateType {
    PREFERENCIA_USUARIO,
    INSTITUCIONAL,
    PROCESSUAL,
    JURIDICA_VALIDADA,
    NEGATIVA,
    RITO_PROCESSUAL_PATTERN,
    PECA_PROCESSUAL_PATTERN,
    ERRO_RECORRENTE,
    SOLUCAO_REUTILIZAVEL,
    PREFERENCIA_OPERACIONAL
}
