package com.tcc.pjb.backend.model.entity;

public enum Especie {
    COMUM, ESPECIAL, FEDERAL, SUMARIO, SUMARISSIMO,
    MONITORIO, EXECUTIVO, INCIDENTE, ARBITRAGEM,
    PROCESSO_ADMINISTRATIVO, PROCESSO_ELEITORAL, PROCESSO_MILITAR
}