apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod-sovereign-adaptive-mesh
  - priorityclass-judicial-lanes.yaml
  - quota-priority-critical.yaml
  - quota-priority-high.yaml
  - quota-priority-bulk.yaml
  - validating-policy-platform-guard.yaml
  - validating-policy-binding-platform-guard.yaml
patches:
  - path: patch-namespace.yaml
  - path: patch-api-deployment.yaml
  - path: patch-worker-deployment.yaml
  - path: patch-api-pdb.yaml
  - path: patch-worker-pdb.yaml
  - path: patch-api-scaledobject.yaml
  - path: patch-worker-scaledobject.yaml
