apiVersion: v1
kind: ResourceQuota
metadata:
  name: pjb-priority-bulk
spec:
  hard:
    pods: "30"
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "20"
    limits.memory: 40Gi
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - pjb-recomposicao-medium
          - pjb-bulk-low
