apiVersion: v1
kind: ResourceQuota
metadata:
  name: pjb-priority-critical
spec:
  hard:
    pods: "40"
    requests.cpu: "24"
    requests.memory: 48Gi
    limits.cpu: "48"
    limits.memory: 96Gi
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - pjb-api-high
          - pjb-custodia-critical
          - pjb-sessao-critical
