apiVersion: v1
kind: ResourceQuota
metadata:
  name: pjb-priority-high
spec:
  hard:
    pods: "60"
    requests.cpu: "32"
    requests.memory: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - pjb-worker-medium
          - pjb-urgencia-sigilo-high
