apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: pjb-platform-guard-binding
spec:
  policyName: pjb-platform-guard
  validationActions:
    - Deny
    - Audit
  matchResources:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pjb
