#!/usr/bin/env bash
set -euo pipefail
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO
\$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PJB_DB_APP_USER}') THEN
        EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE', '${PJB_DB_APP_USER}', '${PJB_DB_APP_PASS}');
    ELSE
        EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE', '${PJB_DB_APP_USER}', '${PJB_DB_APP_PASS}');
    END IF;
END
\$\$;

-- CREATE em nivel de banco (nao so de schema) e exigido pelo Postgres para instalar extensoes
-- "trusted" (pg_trgm, btree_gist, vector) sem superusuario — migrations V219/V257/V302/V307
-- rodam CREATE EXTENSION IF NOT EXISTS e falham com 42501 sem este grant.
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${PJB_DB_APP_USER};
GRANT ALL PRIVILEGES ON SCHEMA public TO ${PJB_DB_APP_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${PJB_DB_APP_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${PJB_DB_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ${PJB_DB_APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${PJB_DB_APP_USER};
SQL
