apiVersion: v1
kind: ConfigMap
metadata:
  name: pjb-backend-config
data:
  PJB_DB_READ_ROUTING_ENABLED: "true"
  PJB_DB_READ_ROUTING_STRICT: "true"
  PJB_DB_READ_VERIFY_TOPOLOGY_ON_STARTUP: "true"
  PJB_DB_READ_URL: jdbc:postgresql://postgresql-ro.database.svc.cluster.local:5432/pjb
  PJB_DB_READ_USER: pjb
  PJB_DB_READ_POOL_MAX: "24"
  PJB_DB_READ_POOL_MIN: "4"
  PJB_DB_READ_PROPAGATION_ENABLED: "true"
  PJB_DB_READ_PROPAGATION_SECURE_COOKIE: "true"

  PJB_DB_READ_OBSERVABILITY_REFRESH_TTL: "5s"
  PJB_DB_READ_OBSERVABILITY_CONNECTION_TIMEOUT: "2s"
  PJB_DB_READ_OBSERVABILITY_STATEMENT_TIMEOUT: "2s"
  PJB_DB_READ_REGIONAL_SELECTION_ENABLED: "true"
  PJB_DB_WRITE_FAILOVER_ENABLED: "false"
  PJB_API_DB_PRESSURE_SHIELD_ENABLED: "true"

  PJB_API_FUNCTIONAL_AVAILABILITY_ENABLED: "true"
  PJB_API_DOMAIN_PETICIONAMENTO_ENABLED: "true"
  PJB_API_DOMAIN_CONSULTA_ENABLED: "true"
  PJB_API_DOMAIN_OPERACAO_INTERNA_ENABLED: "true"
