package com.tcc.pjb.backend.ai.legalai.audit.domain;

public enum LegalAiAuditAction {
    DREAM_CRIADO,
    DREAM_CONCLUIDO,
    DREAM_FALHOU,
    DREAM_CANCELADO,
    STORE_CRIADO,
    STORE_ARQUIVADO,
    CANDIDATO_DETECTADO,
    CANDIDATO_APROVADO,
    CANDIDATO_REJEITADO,
    MEMORIA_PROMOVIDA,
    MEMORIA_INATIVADA,
    CONTRADICAO_DETECTADA,
    INPUT_INJECTION_BLOQUEADO
}
