listen_addresses = '*'
password_encryption = scram-sha-256
shared_preload_libraries = 'pg_stat_statements'
compute_query_id = auto
track_io_timing = on
shared_buffers = 512MB
effective_cache_size = 1536MB
maintenance_work_mem = 256MB
wal_compression = on
max_wal_size = 4GB
min_wal_size = 1GB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
effective_io_concurrency = 200
random_page_cost = 1.1
max_connections = 400
idle_in_transaction_session_timeout = 60000
statement_timeout = 300000
lock_timeout = 15000
log_lock_waits = on
log_min_duration_statement = 500
pg_stat_statements.max = 10000
pg_stat_statements.track = top
pg_stat_statements.track_utility = on
