apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: pjb-service-accounts-critical
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 700
  priorityLevelConfiguration:
    name: pjb-platform-critical
  rules:
    - subjects:
        - kind: Group
          group:
            name: system:serviceaccounts:pjb
      resourceRules:
        - verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
          apiGroups:
            - coordination.k8s.io
          resources:
            - leases
          namespaces:
            - pjb
