apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: pjb-service-accounts-bulk-events
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 750
  priorityLevelConfiguration:
    name: pjb-platform-bulk
  rules:
    - subjects:
        - kind: Group
          group:
            name: system:serviceaccounts:pjb
      resourceRules:
        - verbs:
            - list
            - watch
          apiGroups:
            - ""
          resources:
            - events
            - configmaps
          namespaces:
            - pjb
