package com.tcc.pjb.backend.modules.laiane.dto.roles.judge;

public enum JudicialDecisionTemplateCode {
    HOMOLOGACAO_ACORDO,
    HOMOLOGACAO_DESISTENCIA_EXTINCAO_SEM_MERITO,
    RECONHECIMENTO_PROCEDENCIA_HOMOLOGADO,
    MEDIDA_PROTETIVA_URGENTE_MARIA_DA_PENHA,
    TUTELA_URGENTE_LEITO_UTI,
    TUTELA_URGENTE_SAUDE,
    ASSISTENCIA_DECISORIA_GENERICA
}
