package com.tcc.pjb.backend.model.dto.processual.recursal.automation;

import java.util.Set;

public record RecursalAutomationRequest(
        String pronunciamentoJudicial,
        String pretensaoRecursal,
        boolean sucumbenciaReciproca,
        boolean recursoPrincipalInterposto,
        boolean recursoPrincipalConhecido,
        boolean processoFisico,
        boolean autosEletronicos,
        boolean preparoEfetuado,
        boolean preparoInsuficiente,
        boolean feriadoLocalAplicavel,
        boolean feriadoLocalComprovado,
        boolean pretendeEfeitoInfringente,
        boolean contrarrazoesJaProtocoladas,
        boolean inadmissaoRecursoExcepcional,
        boolean divergenciaJurisprudencialInterna,
        boolean renunciaDireitoRecorrer,
        boolean desistiuRecursoInterposto,
        boolean aquiescenciaExpressaOuTacita,
        boolean desejaSustentacaoOral,
        Set<String> fundamentosEmbargos,
        String segmentoJudiciario,
        String ramoProcessual,
        boolean juizadoEspecial,
        boolean origemTribunal,
        String perfilAtuacao,
        boolean usuarioEnvolvidoNosAutos,
        boolean consultaProcessualGenerica) {


    public RecursalAutomationRequest(
            String pronunciamentoJudicial,
            String pretensaoRecursal,
            boolean sucumbenciaReciproca,
            boolean recursoPrincipalInterposto,
            boolean recursoPrincipalConhecido,
            boolean processoFisico,
            boolean autosEletronicos,
            boolean preparoEfetuado,
            boolean preparoInsuficiente,
            boolean feriadoLocalAplicavel,
            boolean feriadoLocalComprovado,
            boolean pretendeEfeitoInfringente,
            boolean contrarrazoesJaProtocoladas,
            boolean inadmissaoRecursoExcepcional,
            boolean divergenciaJurisprudencialInterna,
            boolean renunciaDireitoRecorrer,
            boolean desistiuRecursoInterposto,
            boolean aquiescenciaExpressaOuTacita,
            boolean desejaSustentacaoOral,
            Set<String> fundamentosEmbargos,
            String segmentoJudiciario,
            String ramoProcessual,
            boolean juizadoEspecial,
            boolean origemTribunal,
            String perfilAtuacao) {
        this(
                pronunciamentoJudicial,
                pretensaoRecursal,
                sucumbenciaReciproca,
                recursoPrincipalInterposto,
                recursoPrincipalConhecido,
                processoFisico,
                autosEletronicos,
                preparoEfetuado,
                preparoInsuficiente,
                feriadoLocalAplicavel,
                feriadoLocalComprovado,
                pretendeEfeitoInfringente,
                contrarrazoesJaProtocoladas,
                inadmissaoRecursoExcepcional,
                divergenciaJurisprudencialInterna,
                renunciaDireitoRecorrer,
                desistiuRecursoInterposto,
                aquiescenciaExpressaOuTacita,
                desejaSustentacaoOral,
                fundamentosEmbargos,
                segmentoJudiciario,
                ramoProcessual,
                juizadoEspecial,
                origemTribunal,
                perfilAtuacao,
                true,
                false
        );
    }

    public RecursalAutomationRequest(
            String pronunciamentoJudicial,
            String pretensaoRecursal,
            boolean sucumbenciaReciproca,
            boolean recursoPrincipalInterposto,
            boolean recursoPrincipalConhecido,
            boolean processoFisico,
            boolean autosEletronicos,
            boolean preparoEfetuado,
            boolean preparoInsuficiente,
            boolean feriadoLocalAplicavel,
            boolean feriadoLocalComprovado,
            boolean pretendeEfeitoInfringente,
            boolean contrarrazoesJaProtocoladas,
            boolean inadmissaoRecursoExcepcional,
            boolean divergenciaJurisprudencialInterna,
            boolean renunciaDireitoRecorrer,
            boolean desistiuRecursoInterposto,
            boolean aquiescenciaExpressaOuTacita,
            boolean desejaSustentacaoOral,
            Set<String> fundamentosEmbargos,
            String segmentoJudiciario,
            String ramoProcessual,
            boolean juizadoEspecial,
            boolean origemTribunal) {
        this(
                pronunciamentoJudicial,
                pretensaoRecursal,
                sucumbenciaReciproca,
                recursoPrincipalInterposto,
                recursoPrincipalConhecido,
                processoFisico,
                autosEletronicos,
                preparoEfetuado,
                preparoInsuficiente,
                feriadoLocalAplicavel,
                feriadoLocalComprovado,
                pretendeEfeitoInfringente,
                contrarrazoesJaProtocoladas,
                inadmissaoRecursoExcepcional,
                divergenciaJurisprudencialInterna,
                renunciaDireitoRecorrer,
                desistiuRecursoInterposto,
                aquiescenciaExpressaOuTacita,
                desejaSustentacaoOral,
                fundamentosEmbargos,
                segmentoJudiciario,
                ramoProcessual,
                juizadoEspecial,
                origemTribunal,
                null,
                true,
                false
        );
    }

    public RecursalAutomationRequest(
            String pronunciamentoJudicial,
            String pretensaoRecursal,
            boolean sucumbenciaReciproca,
            boolean recursoPrincipalInterposto,
            boolean recursoPrincipalConhecido,
            boolean processoFisico,
            boolean autosEletronicos,
            boolean preparoEfetuado,
            boolean preparoInsuficiente,
            boolean feriadoLocalAplicavel,
            boolean feriadoLocalComprovado,
            boolean pretendeEfeitoInfringente,
            boolean contrarrazoesJaProtocoladas,
            boolean inadmissaoRecursoExcepcional,
            boolean divergenciaJurisprudencialInterna,
            boolean renunciaDireitoRecorrer,
            boolean desistiuRecursoInterposto,
            boolean aquiescenciaExpressaOuTacita,
            boolean desejaSustentacaoOral,
            Set<String> fundamentosEmbargos) {
        this(
                pronunciamentoJudicial,
                pretensaoRecursal,
                sucumbenciaReciproca,
                recursoPrincipalInterposto,
                recursoPrincipalConhecido,
                processoFisico,
                autosEletronicos,
                preparoEfetuado,
                preparoInsuficiente,
                feriadoLocalAplicavel,
                feriadoLocalComprovado,
                pretendeEfeitoInfringente,
                contrarrazoesJaProtocoladas,
                inadmissaoRecursoExcepcional,
                divergenciaJurisprudencialInterna,
                renunciaDireitoRecorrer,
                desistiuRecursoInterposto,
                aquiescenciaExpressaOuTacita,
                desejaSustentacaoOral,
                fundamentosEmbargos,
                null,
                null,
                false,
                false,
                null,
                true,
                false
        );
    }
}
