apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod-sovereign-zero-trust-data-plane
patchesStrategicMerge:
  - patch-serviceaccount.yaml
  - patch-api-deployment.yaml
  - patch-worker-deployment.yaml
