apiVersion: v1
kind: ServiceAccount
metadata:
  name: pjb-backend
  annotations:
    spiffe.io/spire-managed-identity: "true"
    pjb.jus.br/trust-domain: "spiffe://pjb.jus.br/pjb"
automountServiceAccountToken: true
