alter table tb_work_item
    add column if not exists sem_interesse boolean not null default false;

create index if not exists idx_work_item_sem_interesse
    on tb_work_item (sem_interesse, status);

create table if not exists tb_perito_disponibilidade (
    id bigint generated by default as identity primary key,
    perito_id bigint not null references tb_usuario(id),
    especialidade_codigo varchar(120) not null,
    comarca varchar(120),
    data_inicio date not null,
    data_fim date not null,
    hora_inicio time,
    hora_fim time,
    disponivel boolean not null default true,
    motivo_indisponibilidade varchar(500),
    criado_em timestamp not null default now(),
    atualizado_em timestamp not null default now()
);

create index if not exists idx_perito_disp_lookup
    on tb_perito_disponibilidade (especialidade_codigo, comarca, disponivel, data_inicio, data_fim);
