CREATE TABLE pjb_ciencia_processual (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processo_id           BIGINT NOT NULL,
    usuario_id            BIGINT NOT NULL,
    tipo_ciencia          VARCHAR(50)  NOT NULL,
    canal                 VARCHAR(30)  NOT NULL,
    status                VARCHAR(25)  NOT NULL DEFAULT 'PENDENTE',
    grau_jurisdicao       VARCHAR(15)  NOT NULL,
    rito_processual       VARCHAR(50),
    instancia_tribunal    VARCHAR(20),
    polo_processual       VARCHAR(15),
    recurso_origem_id     BIGINT,
    ato_processual_id     BIGINT,
    numero_processo       VARCHAR(50)  NOT NULL,
    numero_edicao_dje     VARCHAR(20),
    hash_conteudo         VARCHAR(64)  NOT NULL,
    comprovante_hash      VARCHAR(64),
    data_disponibilizacao TIMESTAMPTZ  NOT NULL,
    data_publicacao_dje   TIMESTAMPTZ,
    dies_a_quo            TIMESTAMPTZ,
    data_ciencia          TIMESTAMPTZ,
    data_expiracao        TIMESTAMPTZ,
    prazo_resposta_dias   SMALLINT     NOT NULL DEFAULT 0,
    em_dias_uteis         BOOLEAN      NOT NULL DEFAULT TRUE,
    ip_confirmacao        VARCHAR(45),
    user_agent_hash       VARCHAR(64),
    session_token_hash    VARCHAR(64),
    audit_trail_id        BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_ciencia_processo
        FOREIGN KEY (processo_id) REFERENCES tb_processo(id),
    CONSTRAINT fk_ciencia_usuario
        FOREIGN KEY (usuario_id) REFERENCES tb_usuario(id),
    CONSTRAINT chk_ciencia_confirmada
        CHECK (status != 'CONFIRMADA' OR data_ciencia IS NOT NULL),
    CONSTRAINT chk_ciencia_expiracao
        CHECK (data_expiracao IS NULL
            OR data_expiracao > data_disponibilizacao),
    CONSTRAINT chk_ciencia_dies_a_quo
        CHECK (dies_a_quo IS NULL
            OR dies_a_quo >= data_disponibilizacao),
    CONSTRAINT chk_polo_processual
        CHECK (polo_processual IN ('ATIVO','PASSIVO','TERCEIRO',
                                   'MP','DEFENSOR','PROCURADOR',
                                   'PERITO','TESTEMUNHA', NULL))
);

CREATE UNIQUE INDEX ux_ciencia_ato_usuario
    ON pjb_ciencia_processual(ato_processual_id, usuario_id)
    WHERE ato_processual_id IS NOT NULL;

CREATE INDEX idx_ciencia_processo_status
    ON pjb_ciencia_processual(processo_id, status);

CREATE INDEX idx_ciencia_usuario_pendente
    ON pjb_ciencia_processual(usuario_id, data_expiracao)
    WHERE status = 'PENDENTE';

CREATE INDEX idx_ciencia_expiracao_pendente
    ON pjb_ciencia_processual(data_expiracao)
    WHERE status = 'PENDENTE';

CREATE INDEX idx_ciencia_grau_tribunal
    ON pjb_ciencia_processual(grau_jurisdicao, instancia_tribunal)
    WHERE status = 'PENDENTE';

CREATE INDEX idx_ciencia_recurso_origem
    ON pjb_ciencia_processual(recurso_origem_id)
    WHERE recurso_origem_id IS NOT NULL;
