create table if not exists tb_polo_processual (
    id                  bigint generated by default as identity primary key,
    processo_id         bigint not null,
    identidade_id       uuid,
    usuario_id          bigint,
    tipo_polo           varchar(30) not null,
    tipo_parte          varchar(40) not null,
    nome_completo       varchar(255) not null,
    documento           varchar(20),
    documento_tipo      varchar(10),
    oab_numero          varchar(20),
    oab_uf              varchar(2),
    representado_por_id bigint,
    ativo               boolean not null default true,
    ordem_polo          smallint not null default 0,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),

    constraint fk_polo_processo
        foreign key (processo_id) references tb_processo(id),
    constraint fk_polo_usuario
        foreign key (usuario_id) references tb_usuario(id),
    constraint fk_polo_representado
        foreign key (representado_por_id) references tb_polo_processual(id),
    constraint chk_polo_tipo
        check (tipo_polo in (
            'ATIVO','PASSIVO','TERCEIRO','MINISTERIO_PUBLICO',
            'DEFENSORIA','PROCURADORIA','FAZENDA_PUBLICA',
            'ASSISTENTE_SIMPLES','ASSISTENTE_LITISCONSORCIAL',
            'AMICUS_CURIAE','CURADOR_ESPECIAL','INTERVENIENTE'
        )),
    constraint chk_documento_tipo
        check (documento_tipo in ('CPF','CNPJ','PASSAPORTE') or documento_tipo is null)
);

create index if not exists idx_polo_processo_tipo
    on tb_polo_processual(processo_id, tipo_polo)
    where ativo = true;

create index if not exists idx_polo_usuario
    on tb_polo_processual(usuario_id)
    where usuario_id is not null and ativo = true;

create index if not exists idx_polo_identidade
    on tb_polo_processual(identidade_id)
    where identidade_id is not null;
