create table if not exists pjb_sequencial_numeracao_cnj (
    id              bigint generated by default as identity primary key,
    segmento        smallint not null,
    tribunal        smallint not null,
    unidade         smallint not null,
    ano             smallint not null,
    ultimo_seq      bigint not null default 0,
    updated_at      timestamptz not null default now(),
    constraint ux_seq_cnj unique (segmento, tribunal, unidade, ano)
);
