create table if not exists tb_processo_estado_log (
    id              bigint generated by default as identity primary key,
    processo_id     bigint not null,
    estado_anterior varchar(35),
    estado_novo     varchar(35) not null,
    operador_id     bigint not null,
    motivo          varchar(500),
    created_at      timestamptz not null default now(),
    constraint fk_estado_processo
        foreign key (processo_id) references tb_processo(id),
    constraint fk_estado_operador
        foreign key (operador_id) references tb_usuario(id)
);

create index if not exists idx_estado_log_processo
    on tb_processo_estado_log(processo_id, created_at desc);
