create table if not exists tb_funcao_servidor_judiciario (
    id                  bigint generated by default as identity primary key,
    usuario_id          bigint not null,
    unidade_id          bigint not null,
    funcao              varchar(40) not null,
    data_inicio         date not null,
    data_fim            date,
    ativo               boolean not null default true,
    designado_por_id    bigint,
    portaria_referencia varchar(100),
    created_at          timestamptz not null default now(),

    constraint fk_funcao_usuario
        foreign key (usuario_id) references tb_usuario(id),
    constraint fk_funcao_unidade
        foreign key (unidade_id) references tb_unidade_judiciaria_competencia(id),
    constraint fk_funcao_designador
        foreign key (designado_por_id) references tb_usuario(id),
    constraint chk_funcao_datas
        check (data_fim is null or data_fim > data_inicio)
);

create unique index if not exists ux_funcao_usuario_unidade_ativo
    on tb_funcao_servidor_judiciario(usuario_id, unidade_id, funcao)
    where ativo = true;

create index if not exists idx_funcao_unidade_ativa
    on tb_funcao_servidor_judiciario(unidade_id, funcao)
    where ativo = true;
