create table if not exists tb_conclusao_processual (
    id                  bigint generated by default as identity primary key,
    processo_id         bigint not null,
    magistrado_id       bigint not null,
    servidor_id         bigint not null,
    tipo_conclusao      varchar(30) not null,
    motivo              varchar(500),
    data_conclusao      timestamptz not null default now(),
    data_limite         timestamptz not null,
    data_devolucao      timestamptz,
    status              varchar(20) not null default 'PENDENTE',
    decisao_id          bigint,
    created_at          timestamptz not null default now(),
    constraint fk_conclusao_processo
        foreign key (processo_id) references tb_processo(id),
    constraint fk_conclusao_magistrado
        foreign key (magistrado_id) references tb_usuario(id),
    constraint fk_conclusao_servidor
        foreign key (servidor_id) references tb_usuario(id),
    constraint chk_conclusao_status
        check (status in ('PENDENTE','DEVOLVIDA','EXPIRADA','CANCELADA','DECIDIDA')),
    constraint chk_conclusao_tipo
        check (tipo_conclusao in (
            'PARA_DECISAO','PARA_DESPACHO','PARA_SENTENCA',
            'PARA_VOTO','PARA_RELATORIO','PARA_AUDIENCIA'
        ))
);

create index if not exists idx_conclusao_processo
    on tb_conclusao_processual(processo_id, status);

create index if not exists idx_conclusao_magistrado_pendente
    on tb_conclusao_processual(magistrado_id, data_limite)
    where status = 'PENDENTE';
