create table if not exists tb_pauta_stf (
    id                  bigint generated by default as identity primary key,
    processo_id         bigint not null,
    orgao_julgador      varchar(20) not null,
    tipo_sessao         varchar(20) not null,
    data_pauta          date not null,
    relator_id          bigint not null,
    resultado           varchar(40),
    votos_favoraveis    smallint default 0,
    votos_contrarios    smallint default 0,
    votos_vista         smallint default 0,
    ministros_impedidos smallint default 0,
    data_julgamento     timestamptz,
    placar_detalhado    jsonb,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    constraint fk_pauta_processo
        foreign key (processo_id) references tb_processo(id),
    constraint fk_pauta_relator
        foreign key (relator_id) references tb_usuario(id)
);

create table if not exists tb_pedido_vista_stf (
    id                  bigint generated by default as identity primary key,
    pauta_id            bigint not null,
    ministro_id         bigint not null,
    data_pedido         timestamptz not null default now(),
    data_limite         timestamptz not null,
    data_devolucao      timestamptz,
    status              varchar(20) not null default 'PENDENTE',
    constraint fk_vista_pauta
        foreign key (pauta_id) references tb_pauta_stf(id),
    constraint fk_vista_ministro
        foreign key (ministro_id) references tb_usuario(id),
    constraint chk_vista_status
        check (status in ('PENDENTE','DEVOLVIDO','EXPIRADO'))
);

create table if not exists tb_impedimento_ministro (
    id                  bigint generated by default as identity primary key,
    processo_id         bigint not null,
    ministro_id         bigint not null,
    tipo_impedimento    varchar(30) not null,
    motivo              varchar(500) not null,
    declarado_em        timestamptz not null default now(),
    constraint fk_impedimento_processo
        foreign key (processo_id) references tb_processo(id),
    constraint fk_impedimento_ministro
        foreign key (ministro_id) references tb_usuario(id),
    constraint ux_impedimento_processo_ministro
        unique (processo_id, ministro_id),
    constraint chk_impedimento_tipo
        check (tipo_impedimento in (
            'PARENTESCO','INTERESSE_DIRETO','CLIENTE_ESCRITORIO',
            'FORO_INTIMO','ANTERIOR_PRONUNCIAMENTO'
        ))
);
