create table if not exists tb_carga_processo (
    id              bigint generated by default as identity primary key,
    processo_id     bigint not null,
    responsavel_id  bigint not null,
    unidade_id      bigint not null,
    tipo_carga      varchar(30) not null,
    data_saida      timestamptz not null default now(),
    data_prevista   timestamptz,
    data_retorno    timestamptz,
    status          varchar(20) not null default 'ATIVA',
    volumes         smallint not null default 1,
    observacao      varchar(500),
    created_at      timestamptz not null default now(),
    constraint fk_carga_processo
        foreign key (processo_id) references tb_processo(id),
    constraint fk_carga_responsavel
        foreign key (responsavel_id) references tb_usuario(id),
    constraint fk_carga_unidade
        foreign key (unidade_id) references tb_unidade_judiciaria_competencia(id),
    constraint chk_carga_status
        check (status in ('ATIVA','DEVOLVIDA','EXTRAVIADA')),
    constraint chk_carga_tipo
        check (tipo_carga in (
            'CONCLUSO_GABINETE','VISTA_PARTE','VISTA_MP',
            'DILIGENCIA','PERICIA','CARTORIO_EXTRAJUDICIAL',
            'ARQUIVO','DIGITALIZACAO'
        )),
    constraint chk_carga_volumes
        check (volumes >= 1)
);

create unique index if not exists ux_carga_ativa_processo
    on tb_carga_processo(processo_id)
    where status = 'ATIVA';

create index if not exists idx_carga_responsavel_ativa
    on tb_carga_processo(responsavel_id)
    where status = 'ATIVA';
