create table if not exists tb_funcao_servidor_solicitacao (
    id                  bigint generated by default as identity primary key,
    solicitante_id      bigint not null,
    unidade_id          bigint not null,
    funcao              varchar(40) not null,
    motivo              text,
    status              varchar(20) not null,
    requested_at        timestamptz not null default now(),
    decidido_por_id     bigint,
    decidido_em         timestamptz,
    motivo_rejeicao     text,

    constraint fk_funcao_solicitacao_unidade
        foreign key (unidade_id) references tb_unidade_judiciaria_competencia(id),
    constraint fk_funcao_solicitacao_solicitante
        foreign key (solicitante_id) references tb_usuario(id),
    constraint fk_funcao_solicitacao_decisor
        foreign key (decidido_por_id) references tb_usuario(id)
);

create index if not exists idx_funcao_solicitacao_solicitante_status
    on tb_funcao_servidor_solicitacao(solicitante_id, status);
