apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod-vpa
  - api-scaledobject.yaml
  - worker-scaledobject.yaml
patches:
  - path: delete-api-hpa.yaml
  - path: delete-worker-hpa.yaml
