package com.tcc.pjb.backend.core.comunicacao.institucional.panel.application.catalog;

import com.tcc.pjb.backend.core.comunicacao.institucional.InstitutionalApiRoutes;
import com.tcc.pjb.backend.core.operational.OperationalApiRoutes;
import com.tcc.pjb.backend.core.comunicacao.institucional.panel.domain.InstitutionalPanelBlueprintSpec;
import java.util.List;
import org.springframework.stereotype.Component;

@Component
public class ForumInstitutionalPanelBlueprintCatalog implements InstitutionalPanelBlueprintCatalog {

    @Override
    public List<InstitutionalPanelBlueprintSpec> specs() {
        return List.of(
                spec("FORUM_DIRETORIA", "FORUM", "PAINEL_DIRETORIA_FORUM", "Diretoria do fórum", "Centro de controle da unidade judiciária", InstitutionalApiRoutes.painelExecutivo(),
                                        List.of("fila_geral_de_triagem", "coberturas_substituicoes", "gates_ativos", "redistribuicoes_e_sla", "agenda_audiencias", "salas_e_slots", "calculadora_judicial",
                                                "monitoramento_subfluxos_e_limpeza", "publicacoes_e_prazos", "central_mandados_e_grupos", "auditoria_operacional", "contingencia_e_sobrecarga"),
                                        List.of("nomear_servidor", "autorizar_uso_remoto_certificado", "abrir_plantao", "homologar_lotacao", "propor_janela_audiencia", "operar_pauta", "abrir_calculadora_judicial",
                                                "reorganizar_filas_da_unidade", "configurar_grupo_mandados", "acionar_contingencia_operacional"),
                                        List.of("MFA obrigatório", "Certificado ICP-Brasil", "Rede institucional ou autorização remota da diretoria"),
                                        List.of("Sem decisão jurisdicional", "Sem assinatura de sentença/decisão", "Gestão administrativa ampla"),
                                        List.of("Direção organiza a unidade, mas não substitui o fluxo decisório do magistrado.")),
                spec("FORUM_SECRETARIA", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria do fórum", "Execução operacional e mastigação do fluxo para gabinete e juiz", OperationalApiRoutes.secretariatOperationalSnapshot(),
                                        List.of("mandados_e_certidoes", "expedientes_pendentes", "prazos_de_secretaria", "expedientes_para_gabinete", "agenda_audiencias", "atas_e_presencas", "calculadora_judicial",
                                                "triagem_autuacao_e_reautuacao", "subfluxos_e_filas_paralelas", "publicacoes_intimacoes_e_prazo", "cartas_oficios_editais_alvaras", "conclusos_devolucoes_e_baixa"),
                                        List.of("certificar_ato", "mover_para_gabinete", "ajustar_fila", "registrar_cumprimento", "operar_pauta", "reservar_sala", "abrir_calculadora_judicial",
                                                "autuar_ou_reautuar", "saneamento_filas_e_subfluxos", "marcar_publicacao_ou_ciencia", "encerrar_prazo_ou_certificar_decurso", "preparar_baixa_ou_arquivamento"),
                                        List.of("Nomeação ativa", "Afiliação homologada", "Certificado conforme ato"),
                                        List.of("Sem assinatura jurisdicional final", "Sem alteração de competência material"),
                                        List.of("Secretaria prepara, certifica e organiza o fluxo sem invadir a função jurisdicional.")),
                spec("FORUM_SECRETARIA_FLUXO_DIGITAL", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria do fórum", "Subfluxos, limpeza de filas, atos automáticos e saneamento diário", OperationalApiRoutes.secretariatOperationalQueueSaneamento(),
                                        List.of("controle_de_subfluxos", "fila_ag_analise", "fila_ag_cumprimento", "fila_prazo", "fila_encerramento_de_ato", "limpeza_de_filas"),
                                        List.of("sanear_fila", "remover_fila_paralela_inadequada", "liberar_ato_automatico", "reencaminhar_para_cumprimento", "cobrar_devolucao_documento"),
                                        List.of("Nomeação ativa", "Certificado conforme ato", "Trilha forense de saneamento"),
                                        List.of("Sem alteração de mérito", "Sem supressão de rastreabilidade"),
                                        List.of("Fluxo digital da serventia precisa controlar filas paralelas, atos automáticos e cumprimento cartorário.")),
                spec("FORUM_SECRETARIA_ATOS_E_COMUNICACOES", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria do fórum", "Cartas, ofícios, mandados, editais, alvarás, publicações e controle de ciência", OperationalApiRoutes.secretariatQueueSummary(),
                                        List.of("oficios_cartas_editais_alvaras", "publicacoes_e_intimacoes", "controle_de_decurso", "mandados_de_saida", "retornos_e_certidoes"),
                                        List.of("expedir_oficio", "expedir_carta", "expedir_edital", "expedir_alvara", "certificar_decurso", "lançar_ciencia"),
                                        List.of("Nomeação ativa", "Certificado quando o ato exigir"),
                                        List.of("Sem assinatura jurisdicional final"),
                                        List.of("Secretaria deve operar os atos de cumprimento sem misturar emissão jurisdicional com expediente cartorário.")),
                spec("FORUM_SECRETARIA_CONCLUSOES_E_BAIXA", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria do fórum", "Conclusão, retorno do gabinete, baixa, remessa e arquivamento controlados", OperationalApiRoutes.secretariatOperationalSnapshot(),
                                        List.of("conclusos_para_gabinete", "retornos_do_gabinete", "transito_e_baixa", "remessa_arquivamento_e_desarquivamento", "controle_de_prevencao_e_redistribuicao"),
                                        List.of("preparar_conclusao", "registrar_retorno_gabinete", "preparar_baixa", "preparar_arquivamento", "sinalizar_prevencao_ou_redistribuicao"),
                                        List.of("Nomeação ativa", "Trilha forense de conclusão e baixa"),
                                        List.of("Sem prolação de decisão", "Sem redefinição material de competência"),
                                        List.of("Conclusão, baixa e remessa exigem trilha própria para evitar mistura entre gabinete, secretaria e vara diversa.")),
                spec("FORUM_DIRETORIA_CONTROLE_OPERACIONAL", "FORUM", "PAINEL_DIRETORIA_FORUM", "Diretoria do fórum", "Governança de filas, produtividade, grupos operacionais e distribuição da capacidade", InstitutionalApiRoutes.painelExecutivo(),
                                        List.of("capacidade_por_unidade", "saneamento_estrutural_de_filas", "grupos_operacionais", "saturacao_de_pauta", "incidentes_operacionais", "upj_e_varas_origem"),
                                        List.of("homologar_saneamento_estrutural", "redistribuir_capacidade", "ativar_contingencia", "configurar_grupos_operacionais", "acompanhar_incidente_operacional"),
                                        List.of("MFA obrigatório", "Certificado ICP-Brasil", "Rede institucional ou autorização remota da diretoria"),
                                        List.of("Sem mérito jurisdicional", "Sem assinatura de sentença/decisão"),
                                        List.of("Diretoria supervisiona a engrenagem operacional da comarca sem romper a independência da vara e do juiz natural.")),
                spec("FORUM_PROTOCOLO_DISTRIBUICAO", "FORUM", "PAINEL_SECRETARIA_FORUM", "Distribuição e protocolo", "Autuação, prevenção, distribuição, redistribuição e saneamento da porta de entrada", OperationalApiRoutes.forumDesksResolve(),
                                        List.of("protocolo_entrada", "autuacao_prevencao_dependencia", "classificacao_e_tarjas", "redistribuicoes_controladas", "malotes_e_encaminhamentos"),
                                        List.of("autuar_ou_reautuar", "validar_prevencao", "ajustar_dependencia", "redistribuir_formalmente", "encaminhar_para_vara_correta"),
                                        List.of("Nomeação ativa", "Certificado conforme ato", "Trilha forte de distribuição"),
                                        List.of("Sem mérito jurisdicional", "Sem conclusão direta ao gabinete sem registro"),
                                        List.of("A porta de entrada precisa separar protocolo, autuação, prevenção e redistribuição para evitar erro estrutural desde o primeiro ato.")),
                spec("FORUM_GABINETE_MAGISTRADO", "FORUM", "PAINEL_UNIDADE", "Gabinete judicial", "Conclusões, minutas, votos, precedentes, urgências e retorno controlado ao cartório", InstitutionalApiRoutes.painelExecutivo("FORUM", "GABINETE"),
                                        List.of("conclusos_do_dia", "minutas_e_modelos", "alertas_de_urgencia", "precedentes_memoria_risco", "retornos_para_secretaria"),
                                        List.of("assumir_conclusao", "priorizar_urgencia", "devolver_para_secretaria", "validar_minuta", "corrigir_fluxo_critico"),
                                        List.of("MFA obrigatório", "Certificado ICP-Brasil quando o ato exigir", "Nomeação ativa do gabinete"),
                                        List.of("Sem login compartilhado do gabinete", "Sem mistura entre gabinete de vara diversa"),
                                        List.of("Gabinete precisa de painel próprio para conclusão, minuta, retorno e supervisão direta do magistrado ou da assessoria autorizada.")),
                spec("FORUM_GABINETE_ASSESSORIA", "FORUM", "PAINEL_UNIDADE", "Assessoria de gabinete", "Fila preparatória para minutas, relatórios, triagem decisória e organização do dossiê do processo", InstitutionalApiRoutes.painelExecutivo("FORUM", "ASSESSORIA"),
                                        List.of("minutas_em_preparo", "relatorios_e_memoria", "pendencias_de_conferencia", "dossie_para_julgamento", "controle_de_retorno"),
                                        List.of("preparar_minuta", "montar_relatorio", "sugerir_encaminhamento", "organizar_dossie", "sinalizar_inconsistencia"),
                                        List.of("Nomeação ativa", "Sem substituição automática do titular"),
                                        List.of("Sem assinatura final", "Sem alterar competência ou sigilo por conta própria"),
                                        List.of("Assessoria do gabinete precisa de trilha própria para preparar minutas, relatórios e dossiês sem romper a autoria do ato final.")),
                spec("FORUM_UPJ_COORDENACAO", "FORUM", "PAINEL_SECRETARIA_FORUM", "UPJ e secretaria compartilhada", "Coordenação de serventia compartilhada com preservação das varas de origem", OperationalApiRoutes.secretariatOperationalSnapshot(),
                                        List.of("varas_origem", "capacidade_compartilhada", "filas_por_origem", "coberturas_e_substituicoes", "gargalos_por_bloco"),
                                        List.of("segmentar_por_vara_origem", "redistribuir_capacidade", "homologar_cobertura", "sanear_filas_compartilhadas", "preservar_independencia_das_varas"),
                                        List.of("Nomeação ativa", "Trilha forense da UPJ"),
                                        List.of("Sem fusão cega das varas", "Sem apagar a autoria do feito de origem"),
                                        List.of("UPJ compartilha estrutura e produtividade, mas o processo precisa continuar amarrado à vara de origem e ao seu fluxo próprio.")),
                spec("FORUM_SECRETARIA_JUIZADOS", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria dos juizados", "Sessões, termos, intimações céleres, balcão e cumprimento enxuto do rito especial", OperationalApiRoutes.secretariatQueueSummary(),
                                        List.of("sessoes_e_pautas_enxutas", "termos_e_atas", "citacoes_e_intimacoes_curtas", "cumprimentos_rapidos", "retorno_ao_juizado"),
                                        List.of("marcar_sessao", "gerar_termo", "lançar_ciencia", "encerrar_cumprimento", "organizar_retorno"),
                                        List.of("Nomeação ativa", "Trilha específica do juizado"),
                                        List.of("Sem importar rotina pesada de vara comum quando incompatível com o rito"),
                                        List.of("Juizados exigem fluxo mais enxuto, com forte foco em sessão, termo, celeridade e comunicação direta.")),
                spec("FORUM_SEGUNDO_GRAU_SECRETARIA", "FORUM", "PAINEL_UNIDADE", "Secretaria de 2º grau e órgão colegiado", "Pauta colegiada, sessão, prevenção recursal, acórdãos, intimações e retorno ao órgão julgador", OperationalApiRoutes.processualPendenciasPainel(),
                                        List.of("pauta_colegiada", "mesa_de_sessao", "prevencao_recursal", "acordaos_e_publicacoes", "retornos_para_orgao_julgador"),
                                        List.of("organizar_pauta_colegiada", "preparar_sessao", "controlar_prevencao_recursal", "publicar_acordao", "encaminhar_retorno"),
                                        List.of("Nomeação ativa", "Certificado conforme ato colegiado"),
                                        List.of("Sem invadir o voto do relator ou do colegiado"),
                                        List.of("No 2º grau, secretaria e apoio precisam controlar pauta colegiada, prevenção, sessão, acórdão e comunicação sem duplicar o gabinete do relator.")),
                spec("FORUM_SECRETARIA_CIVEL_CUMPRIMENTO", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria cível", "Citação, intimação, saneamento, instrução, cumprimento e cartas precatórias na trilha cível", OperationalApiRoutes.secretariatQueueSummary(),
                                        List.of("citacoes_intimacoes_e_decurso", "saneamento_e_instrucao", "cumprimento_de_sentenca", "cartas_precatorias_e_retorno", "controle_de_audiencias_civeis"),
                                        List.of("expedir_citacao", "marcar_decurso", "preparar_conclusao_civel", "acompanhar_cumprimento", "gerir_carta_precatoria"),
                                        List.of("Nomeação ativa", "Trilha cível segregada por vara e especialização"),
                                        List.of("Sem decisão de mérito", "Sem alteração de competência material sem fluxo formal"),
                                        List.of("A secretaria cível precisa de trilha própria para citação, saneamento, instrução e cumprimento sem se misturar ao penal ou ao recursal.")),
                spec("FORUM_SECRETARIA_PENAL_CUSTODIA", "FORUM", "PAINEL_SECRETARIA_FORUM", "Secretaria criminal", "Custódia, júri, audiências penais, mandados e comunicações urgentes do rito criminal", OperationalApiRoutes.secretariatOperationalSnapshot(),
                                        List.of("audiencias_penais_e_custodia", "mandados_penais", "intimacoes_do_mp_defesa_e_reu", "juri_e_sessoes", "devolucao_e_cadeia_de_custodia_documental"),
                                        List.of("organizar_audiencia_penal", "expedir_mandado_penal", "confirmar_apresentacao_custodial", "registrar_termo_penal", "certificar_retorno_urgente"),
                                        List.of("Nomeação ativa", "Trilha penal segregada", "Controle reforçado de urgência"),
                                        List.of("Sem mistura com rito cível", "Sem redefinição de pauta ou competência sem ordem formal"),
                                        List.of("A secretaria criminal precisa operar custódia, júri, mandados e comunicações urgentes em painel próprio e segregado.")),
                spec("FORUM_GABINETE_DECISOES_E_PRECEDENTES", "FORUM", "PAINEL_UNIDADE", "Gabinete judicial", "Bloco reservado para conclusões, precedentes, votos, minutas e devoluções qualificadas", InstitutionalApiRoutes.painelExecutivo("FORUM", "GABINETE"),
                                        List.of("conclusoes_reservadas", "precedentes_e_memoria", "minutas_votos_e_modelos", "controle_de_devolucao", "alertas_de_prioridade"),
                                        List.of("priorizar_conclusao", "organizar_precedente", "qualificar_minuta", "devolver_para_secretaria", "corrigir_fluxo_critico"),
                                        List.of("MFA obrigatório", "Nomeação ativa do gabinete"),
                                        List.of("Sem compartilhamento indevido entre gabinetes", "Sem atuação cartorária genérica"),
                                        List.of("Gabinete precisa de bloco ainda mais reservado para conclusão, precedentes, modelos e devoluções com rastro integral.")),
                spec("FORUM_SEGUNDO_GRAU_ACORDAOS_PUBLICACOES", "FORUM", "PAINEL_UNIDADE", "Secretaria de 2º grau", "Sessão, acórdãos, publicação, prevenção e retorno qualificado do colegiado", OperationalApiRoutes.processualPendenciasPainel(),
                                        List.of("sessao_e_quorum", "acordaos_pendentes", "publicacoes_e_intimacoes", "prevencao_recursal", "retornos_para_gabinete_e_orgao"),
                                        List.of("fechar_sessao", "publicar_acordao", "intimar_partes", "controlar_prevencao", "encaminhar_retorno_colegiado"),
                                        List.of("Nomeação ativa", "Trilha colegiada formal"),
                                        List.of("Sem invadir gabinete do relator", "Sem alterar composição colegiada sem fluxo formal"),
                                        List.of("No 2º grau, acórdão, publicação e retorno do colegiado exigem camada própria além da pauta da sessão."))
        );
    }

    private InstitutionalPanelBlueprintSpec spec(String codigo,
                                                 String escopo,
                                                 String panel,
                                                 String audience,
                                                 String titulo,
                                                 String rota,
                                                 List<String> secoes,
                                                 List<String> acoes,
                                                 List<String> guardas,
                                                 List<String> visibilidade,
                                                 List<String> fundamentos) {
        return new InstitutionalPanelBlueprintSpec(codigo, escopo, panel, audience, titulo, rota, secoes, acoes, guardas, visibilidade, fundamentos);
    }
}
