package com.tcc.pjb.backend.modules.acordo.domain;

public enum AcordoMomentoProcessual {
    ANTES_CONTESTACAO,
    ANTES_AUDIENCIA_CONCILIACAO_MEDIACAO,
    APOS_CONTESTACAO_COM_PROPOSTA,
    APOS_PERICIA_LAUDO,
    ANTES_SENTENCA,
    RECURSAL,
    CUMPRIMENTO_SENTENCA_EXECUCAO,
    MUTIRAO_CONCILIACAO,
    REQUERIMENTO_PARTE,
    DETERMINACAO_JUDICIAL_CEJUSC,
    FORA_JANELA
}
