apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pjb
commonLabels:
  app.kubernetes.io/name: pjb
  app.kubernetes.io/part-of: pjb
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - api-priorityclass.yaml
  - worker-priorityclass.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-service.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - stream-ingress.yaml
  - api-hpa.yaml
  - worker-hpa.yaml
  - api-pdb.yaml
  - worker-pdb.yaml
