apiVersion: v1
kind: Service
metadata:
  name: pjb-worker
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: 8080
      targetPort: http
