package com.tcc.pjb.backend.core.comunicacao.institucional.audit.domain;

public enum InstitutionalTimelineEventType {
    COMUNICACAO_DISPONIBILIZADA,
    COMUNICACAO_RECEBIDA,
    COMUNICACAO_REDISTRIBUIDA,
    COMUNICACAO_CIENTIFICADA,
    CERTIDAO_GERADA,
    COMUNICACAO_CUMPRIDA,
    ENTREGA_ENFILEIRADA,
    ENTREGA_TENTADA,
    ENTREGA_ENCAMINHADA,
    ENTREGA_CONFIRMADA,
    ENTREGA_RETRY_AGENDADO,
    ENTREGA_FALHA_TERMINAL,
    ENTREGA_MOVIDA_DLQ,
    GATE_CRIADO,
    GATE_TRANSICIONADO,
    GATE_LIBERADO,
    DELEGACAO_REGISTRADA,
    SUBSTITUICAO_REGISTRADA,
    MINUTA_CRIADA,
    MINUTA_ENCAMINHADA_APROVACAO,
    MINUTA_APROVADA,
    MINUTA_REJEITADA,
    CERTIDAO_NAO_LEITURA_GERADA,
    AVISO_EXTERNO_ENFILEIRADO
}
