package com.tcc.pjb.backend.core.jobs.domain;

public enum JobType {
    BULK_FINALIZE_ATTACHMENTS,
    SECRETARIAT_TRIAGE_REINDEX,
    BULK_NOTIFY,
    BULK_SIGN,
    BULK_EXPORT,
    ADV_CLIENTE_CANONICALIZE_SENSITIVE,
    LAIANE_PROTOCOL_SUBMIT_PJE,
    PJB_SUBSTITUICAO_NACIONAL_EXECUCAO,
    MNI_BATCH_MIGRATION
}
