apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: pjb-backend
    newName: pjb-backend
    newTag: local
patches:
  - path: patch-api.yaml
  - path: patch-worker.yaml
  - path: patch-ingress.yaml
