apiVersion: v1
kind: ConfigMap
metadata:
  name: pjb-opa-ext-authz-policy
  namespace: pjb
  labels:
    app.kubernetes.io/name: pjb-opa-ext-authz-policy
    app.kubernetes.io/part-of: pjb-sovereign-edge
data:
  policy.rego: |
    package envoy.authz

    default allow := false

    critical_paths := {
      "/api/v1/mp/recurso/",
      "/api/v1/distribuicao/processual/processos/"
    }

    read_only := lower(object.get(input.attributes.request.http.headers, "x-pjb-rls-read-only", "false")) == "true"

    allow if {
      startswith(input.attributes.request.http.path, "/api/v1/institucional/")
      object.get(input.attributes.request.http.headers, "x-pjb-affiliation-id", "") != ""
    }

    allow if {
      some p in critical_paths
      startswith(input.attributes.request.http.path, p)
      object.get(input.attributes.request.http.headers, "x-pjb-affiliation-id", "") != ""
      not read_only
    }
