package com.tcc.pjb.backend.core.comunicacao.institucional.entry.domain;

public enum InstitutionalEntryLandingPanel {
    PAINEL_ORGAO,
    PAINEL_UNIDADE,
    PAINEL_CAIXA,
    PAINEL_TITULAR,
    PAINEL_TRIAGEM,
    PAINEL_APOIO_TECNICO,
    PAINEL_SECRETARIA_FORUM,
    PAINEL_AUDIENCIAS_CONCILIACAO,
    PAINEL_DIRETORIA_FORUM,
    PAINEL_DELEGACIA,
    PAINEL_CUSTODIA_PRISIONAL,
    PAINEL_TECNICO_JUDICIAL,
    PAINEL_COOPERACAO_JUDICIAL,
    PAINEL_ADMINISTRATIVO
}
