package com.tcc.pjb.backend.integration.judicial.security;

public enum JudicialConnectorCryptographicFailureType {
    SSL_CONTEXT_RESOLUTION_FAILURE,
    KEYSTORE_LOAD_FAILURE,
    TRUSTSTORE_LOAD_FAILURE,
    PKCS11_PROVIDER_FAILURE,
    KEY_MATERIAL_ACCESS_FAILURE,
    CERTIFICATE_VALIDATION_FAILURE,
    CLIENT_CERTIFICATE_SELECTION_FAILURE,
    TLS_HANDSHAKE_FAILURE,
    TLS_PROTOCOL_FAILURE,
    TLS_IO_FAILURE,
    SIGNATURE_KEY_FAILURE,
    SIGNATURE_EXECUTION_FAILURE,
    SECURITY_CONFIGURATION_FAILURE,
    UNCLASSIFIED_CRYPTOGRAPHIC_FAILURE
}
