from __future__ import annotations

EXTRA_STUB_OVERRIDES = {
    'org/springframework/boot/SpringApplication.java': 'package org.springframework.boot; public final class SpringApplication { private SpringApplication(){} public static Object run(Class<?> source, String... args){ return null; } }',
    'org/springframework/boot/autoconfigure/SpringBootApplication.java': 'package org.springframework.boot.autoconfigure; public @interface SpringBootApplication { Class<?>[] scanBasePackageClasses() default {}; String[] scanBasePackages() default {}; }',
    'org/springframework/boot/context/properties/ConfigurationPropertiesScan.java': 'package org.springframework.boot.context.properties; public @interface ConfigurationPropertiesScan { String[] basePackages() default {}; Class<?>[] basePackageClasses() default {}; }',
    'org/springframework/cache/annotation/EnableCaching.java': 'package org.springframework.cache.annotation; public @interface EnableCaching {}',
    'org/springframework/scheduling/annotation/EnableAsync.java': 'package org.springframework.scheduling.annotation; public @interface EnableAsync { boolean proxyTargetClass() default false; }',
    'org/springframework/scheduling/annotation/EnableScheduling.java': 'package org.springframework.scheduling.annotation; public @interface EnableScheduling {}',
    'org/springframework/context/ApplicationContext.java': 'package org.springframework.context; import java.util.Map; public interface ApplicationContext { <T> T getBean(Class<T> requiredType); Object getBean(String name); <T> Map<String,T> getBeansOfType(Class<T> type); }',
    'org/springframework/context/annotation/Configuration.java': 'package org.springframework.context.annotation; public @interface Configuration { boolean proxyBeanMethods() default true; }',
    'org/springframework/context/annotation/Bean.java': 'package org.springframework.context.annotation; public @interface Bean { String[] value() default {}; }',
    'org/springframework/context/annotation/Profile.java': 'package org.springframework.context.annotation; public @interface Profile { String[] value(); }',
    'org/springframework/context/event/EventListener.java': 'package org.springframework.context.event; public @interface EventListener { Class<?>[] value() default {}; Class<?>[] classes() default {}; String condition() default ""; }',
    'org/springframework/stereotype/Component.java': 'package org.springframework.stereotype; public @interface Component { String value() default ""; }',
    'org/springframework/stereotype/Service.java': 'package org.springframework.stereotype; public @interface Service { String value() default ""; }',
    'org/springframework/stereotype/Repository.java': 'package org.springframework.stereotype; public @interface Repository { String value() default ""; }',
    'org/springframework/beans/factory/annotation/Autowired.java': 'package org.springframework.beans.factory.annotation; public @interface Autowired { boolean required() default true; }',
    'org/springframework/beans/factory/annotation/Qualifier.java': 'package org.springframework.beans.factory.annotation; public @interface Qualifier { String value() default ""; }',
    'org/springframework/beans/factory/annotation/Value.java': 'package org.springframework.beans.factory.annotation; public @interface Value { String value(); }',
    'org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.java': 'package org.springframework.boot.autoconfigure.condition; public @interface ConditionalOnProperty { String prefix() default ""; String[] name() default {}; String havingValue() default ""; boolean matchIfMissing() default false; }',
    'org/springframework/web/socket/CloseStatus.java': 'package org.springframework.web.socket; public class CloseStatus { public static final CloseStatus NORMAL = new CloseStatus(); public int getCode(){ return 1000; } }',
    'org/springframework/web/socket/TextMessage.java': 'package org.springframework.web.socket; public class TextMessage { private final String payload; public TextMessage(String payload){ this.payload = payload; } public String getPayload(){ return payload; } }',
    'org/springframework/web/socket/WebSocketSession.java': 'package org.springframework.web.socket; import java.net.URI; import java.security.Principal; import java.util.Map; public interface WebSocketSession { String getId(); URI getUri(); Principal getPrincipal(); Map<String,Object> getAttributes(); void sendMessage(TextMessage message) throws Exception; boolean isOpen(); }',
    'org/springframework/data/domain/Pageable.java': 'package org.springframework.data.domain; public interface Pageable {}',
    'org/springframework/data/domain/PageRequest.java': 'package org.springframework.data.domain; public final class PageRequest implements Pageable { private PageRequest(){} public static PageRequest of(int page, int size){ return new PageRequest(); } public static PageRequest of(int page, int size, Sort sort){ return new PageRequest(); } }',
    'org/springframework/data/domain/Sort.java': 'package org.springframework.data.domain; public class Sort { public enum Direction { ASC, DESC } public static Sort by(String... properties){ return new Sort(); } public static Sort by(Direction direction, String... properties){ return new Sort(); } public Sort descending(){ return this; } public Sort ascending(){ return this; } }',
    'lombok/AccessLevel.java': 'package lombok; public enum AccessLevel { PUBLIC, MODULE, PROTECTED, PACKAGE, PRIVATE }',
    'lombok/Getter.java': 'package lombok; public @interface Getter { lombok.AccessLevel value() default lombok.AccessLevel.PUBLIC; }',
    'lombok/Setter.java': 'package lombok; public @interface Setter { lombok.AccessLevel value() default lombok.AccessLevel.PUBLIC; }',
    'lombok/Builder.java': 'package lombok; public @interface Builder { boolean toBuilder() default false; String builderMethodName() default "builder"; public @interface Default {} }',
    'lombok/Data.java': 'package lombok; public @interface Data {}',
    'lombok/NoArgsConstructor.java': 'package lombok; public @interface NoArgsConstructor { lombok.AccessLevel access() default lombok.AccessLevel.PUBLIC; }',
    'lombok/AllArgsConstructor.java': 'package lombok; public @interface AllArgsConstructor { lombok.AccessLevel access() default lombok.AccessLevel.PUBLIC; }',
    'lombok/RequiredArgsConstructor.java': 'package lombok; public @interface RequiredArgsConstructor { lombok.AccessLevel access() default lombok.AccessLevel.PUBLIC; }',
    'lombok/EqualsAndHashCode.java': 'package lombok; public @interface EqualsAndHashCode { boolean callSuper() default false; String[] of() default {}; }',
    'lombok/ToString.java': 'package lombok; public @interface ToString { boolean callSuper() default false; String[] of() default {}; }',
    'lombok/Value.java': 'package lombok; public @interface Value {}',
    'lombok/extern/slf4j/Slf4j.java': 'package lombok.extern.slf4j; public @interface Slf4j {}',
    'com/fasterxml/jackson/core/type/TypeReference.java': 'package com.fasterxml.jackson.core.type; public abstract class TypeReference<T> {}',
    'com/fasterxml/jackson/annotation/JsonIgnoreProperties.java': 'package com.fasterxml.jackson.annotation; public @interface JsonIgnoreProperties { String[] value() default {}; boolean ignoreUnknown() default false; }',
    'com/fasterxml/jackson/annotation/JsonProperty.java': 'package com.fasterxml.jackson.annotation; public @interface JsonProperty { String value() default ""; }',
    'com/fasterxml/jackson/annotation/JsonInclude.java': 'package com.fasterxml.jackson.annotation; public @interface JsonInclude { Include value() default Include.ALWAYS; public enum Include { ALWAYS, NON_NULL, NON_EMPTY } }',
    'org/hibernate/annotations/CreationTimestamp.java': 'package org.hibernate.annotations; public @interface CreationTimestamp {}',
    'org/hibernate/annotations/UpdateTimestamp.java': 'package org.hibernate.annotations; public @interface UpdateTimestamp {}',
    'org/hibernate/annotations/JdbcTypeCode.java': 'package org.hibernate.annotations; public @interface JdbcTypeCode { int value(); }',
}

KNOWN_ANNOTATION_FQCNS = {
    'org.springframework.boot.autoconfigure.SpringBootApplication',
    'org.springframework.boot.context.properties.ConfigurationPropertiesScan',
    'org.springframework.cache.annotation.EnableCaching',
    'org.springframework.scheduling.annotation.EnableAsync',
    'org.springframework.scheduling.annotation.EnableScheduling',
    'org.springframework.context.annotation.Configuration',
    'org.springframework.context.annotation.Bean',
    'org.springframework.context.annotation.Profile',
    'org.springframework.context.event.EventListener',
    'org.springframework.stereotype.Component',
    'org.springframework.stereotype.Service',
    'org.springframework.stereotype.Repository',
    'org.springframework.boot.autoconfigure.condition.ConditionalOnProperty',
    'org.springframework.beans.factory.annotation.Autowired',
    'org.springframework.beans.factory.annotation.Qualifier',
    'org.springframework.beans.factory.annotation.Value',
    'lombok.Getter',
    'lombok.Setter',
    'lombok.Builder',
    'lombok.Data',
    'lombok.NoArgsConstructor',
    'lombok.AllArgsConstructor',
    'lombok.RequiredArgsConstructor',
    'lombok.EqualsAndHashCode',
    'lombok.ToString',
    'lombok.Value',
    'lombok.extern.slf4j.Slf4j',
    'com.fasterxml.jackson.annotation.JsonIgnoreProperties',
    'com.fasterxml.jackson.annotation.JsonProperty',
    'com.fasterxml.jackson.annotation.JsonInclude',
    'org.hibernate.annotations.CreationTimestamp',
    'org.hibernate.annotations.UpdateTimestamp',
    'org.hibernate.annotations.JdbcTypeCode',
}

NESTED_ENUM_NAMES = {
    'AppendMode',
    'Direction',
    'Include',
    'AccessLevel',
}
