package com.tcc.pjb.backend.core.comunicacao.institucional.panel.application;

import com.tcc.pjb.backend.core.comunicacao.institucional.panel.domain.InstitutionalHearingRiteGovernance;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

class InstitutionalHearingCivilAndJuizadosRiteResolver {

    private final InstitutionalHearingRiteGovernanceFactory factory;

    InstitutionalHearingCivilAndJuizadosRiteResolver(InstitutionalHearingRiteGovernanceFactory factory) {
        this.factory = factory;
    }

    List<InstitutionalHearingRiteGovernance> resolve(InstitutionalHearingRiteGovernanceContext context) {
        ArrayList<InstitutionalHearingRiteGovernance> rites = new ArrayList<>();

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "CIVEL_COMUM",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "COMUM",
                        "COMUM",
                        "INSTRUCAO_E_CONCILIACAO",
                        context.civilBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        context.requiresSecretariatCoordination(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaminhar_para_pauta_civel", "validar_sala_e_link", "conferir_partes_e_representacoes"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "CIVEL", context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "CIVEL_ESTADUAL_COMUM",
                        "JUSTICA_ESTADUAL",
                        "ESTADUAL",
                        "COMUM",
                        "INSTRUCAO_E_CONCILIACAO_ESTADUAL",
                        context.civilBroad() && context.broadCommonScope(),
                        context.canRequestHearing() && context.broadCommonScope(),
                        context.canSuggestSlot() && context.broadCommonScope(),
                        context.canOperationallySchedule() && context.broadCommonScope(),
                        context.canReschedule() && context.broadCommonScope(),
                        context.canCancel() && context.broadCommonScope(),
                        context.canReserveRoom() && context.broadCommonScope(),
                        context.canManageVirtualRoom() && context.broadCommonScope(),
                        context.canConfirmAttendance() && context.broadCommonScope(),
                        context.canRecordTerm() && context.broadCommonScope(),
                        context.canIssueHearingCommunications() && context.broadCommonScope(),
                        context.canPrepareHearingBundle() && context.broadCommonScope(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization() && context.broadCommonScope(),
                        context.requiresSecretariatCoordination() && context.broadCommonScope(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_em_pauta_da_vara_estadual", "separar_audiencia_por_foro_e_competencia"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "CIVEL", "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "CIVEL_FEDERAL_COMUM",
                        "JUSTICA_FEDERAL",
                        "FEDERAL",
                        "COMUM",
                        "INSTRUCAO_E_CONCILIACAO_FEDERAL",
                        context.civilBroad() && context.federalScope(),
                        context.canRequestHearing() && context.federalScope(),
                        context.canSuggestSlot() && context.federalScope(),
                        context.canOperationallySchedule() && context.federalScope(),
                        context.canReschedule() && context.federalScope(),
                        context.canCancel() && context.federalScope(),
                        context.canReserveRoom() && context.federalScope(),
                        context.canManageVirtualRoom() && context.federalScope(),
                        context.canConfirmAttendance() && context.federalScope(),
                        context.canRecordTerm() && context.federalScope(),
                        context.canIssueHearingCommunications() && context.federalScope(),
                        context.canPrepareHearingBundle() && context.federalScope(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization() && context.federalScope(),
                        context.requiresSecretariatCoordination() && context.federalScope(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_em_pauta_da_vara_federal", "validar_competencia_justica_federal"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "CIVEL", "FEDERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "JUIZADOS",
                        "JUIZADOS_ESPECIAIS",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "JUIZADOS",
                        "ESPECIAL",
                        "CONCILIACAO_INSTRUCAO",
                        context.juizadosBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        context.requiresSecretariatCoordination(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("organizar_pauta_conciliacao_juizados", "confirmar_comparecimento_rapido"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "JUIZADOS", "ESPECIAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "JUIZADO_ESPECIAL_CIVEL",
                        "JUIZADOS_ESPECIAIS",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "JUIZADOS",
                        "ESPECIAL_CIVEL",
                        "CONCILIACAO_E_INSTRUCAO_JEC",
                        context.juizadosBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        context.requiresSecretariatCoordination(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("organizar_termo_e_conciliacao_jec"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "JEC", "CIVEL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "JUIZADO_ESPECIAL_CRIMINAL",
                        "JUIZADOS_ESPECIAIS_CRIMINAIS",
                        context.broadCommonScope() ? "ESTADUAL" : "JECRIM",
                        "ESPECIAL_CRIMINAL",
                        "AUDIENCIA_PRELIMINAR_OU_INSTRUCAO",
                        context.juizadosBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        context.requiresSecretariatCoordination(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("organizar_audiencia_preliminar_jecrim", "intimar_mp_defesa_ofendido"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "JECRIM", "PENAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "JUIZADO_FAZENDA_PUBLICA",
                        "JUIZADOS_FAZENDA_PUBLICA",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "FAZENDA",
                        "ESPECIAL_FAZENDA",
                        "CONCILIACAO_OU_INSTRUCAO_COM_ENTE_PUBLICO",
                        context.publicTreasuryBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("validar_representacao_do_ente_publico", "confirmar_ciencia_da_procuradoria"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "JEFAZ", "FAZENDA")));

        return List.copyOf(rites);
    }
}
