package com.tcc.pjb.backend.core.comunicacao.institucional.panel.application;

import com.tcc.pjb.backend.core.comunicacao.institucional.panel.domain.InstitutionalHearingRiteGovernance;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

class InstitutionalHearingSpecializedJusticeRiteResolver {

    private final InstitutionalHearingRiteGovernanceFactory factory;

    InstitutionalHearingSpecializedJusticeRiteResolver(InstitutionalHearingRiteGovernanceFactory factory) {
        this.factory = factory;
    }

    List<InstitutionalHearingRiteGovernance> resolve(InstitutionalHearingRiteGovernanceContext context) {
        ArrayList<InstitutionalHearingRiteGovernance> rites = new ArrayList<>();

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "TRABALHISTA",
                        "JUSTICA_DO_TRABALHO",
                        "TRABALHO",
                        "COMUM",
                        "AUDIENCIA_UNA_OU_INSTRUTORIA",
                        context.sectionVisible() && context.laborScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.laborScope(),
                        context.canSuggestSlot() && context.laborScope(),
                        context.canOperationallySchedule() && context.laborScope(),
                        context.canReschedule() && context.laborScope(),
                        context.canCancel() && context.laborScope(),
                        context.canReserveRoom() && context.laborScope(),
                        context.canManageVirtualRoom() && context.laborScope(),
                        context.canConfirmAttendance() && context.laborScope(),
                        context.canRecordTerm() && context.laborScope(),
                        context.canIssueHearingCommunications() && context.laborScope(),
                        context.canPrepareHearingBundle() && context.laborScope(),
                        context.requiresUnitIsolation(),
                        true,
                        context.requiresSecretariatCoordination() && context.laborScope(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("configurar_audiencia_una_ou_faseada", "intimar_partes_e_testemunhas_pelo_fluxo_trabalhista"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_LABOR_SPLIT_WITHOUT_CAUSE),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "TRABALHISTA", "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "TRABALHISTA_CONHECIMENTO",
                        "JUSTICA_DO_TRABALHO",
                        "TRABALHO",
                        "CONHECIMENTO",
                        "AUDIENCIA_UNA_DE_CONHECIMENTO",
                        context.sectionVisible() && context.laborScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.laborScope(),
                        context.canSuggestSlot() && context.laborScope(),
                        context.canOperationallySchedule() && context.laborScope(),
                        context.canReschedule() && context.laborScope(),
                        context.canCancel() && context.laborScope(),
                        context.canReserveRoom() && context.laborScope(),
                        context.canManageVirtualRoom() && context.laborScope(),
                        context.canConfirmAttendance() && context.laborScope(),
                        context.canRecordTerm() && context.laborScope(),
                        context.canIssueHearingCommunications() && context.laborScope(),
                        context.canPrepareHearingBundle() && context.laborScope(),
                        context.requiresUnitIsolation(),
                        true,
                        context.requiresSecretariatCoordination() && context.laborScope(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("operar_audiencia_una_trabalhista"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_LABOR_SPLIT_WITHOUT_CAUSE),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "TRABALHISTA", "CONHECIMENTO")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "TRABALHISTA_EXECUCAO",
                        "JUSTICA_DO_TRABALHO",
                        "TRABALHO",
                        "EXECUCAO",
                        "AUDIENCIA_EM_EXECUCAO_TRABALHISTA",
                        context.sectionVisible() && context.laborScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.laborScope(),
                        context.canSuggestSlot() && context.laborScope(),
                        context.canOperationallySchedule() && context.laborScope(),
                        context.canReschedule() && context.laborScope(),
                        context.canCancel() && context.laborScope(),
                        context.canReserveRoom() && context.laborScope(),
                        context.canManageVirtualRoom() && context.laborScope(),
                        context.canConfirmAttendance() && context.laborScope(),
                        context.canRecordTerm() && context.laborScope(),
                        context.canIssueHearingCommunications() && context.laborScope(),
                        context.canPrepareHearingBundle() && context.laborScope(),
                        context.requiresUnitIsolation(),
                        true,
                        context.requiresSecretariatCoordination() && context.laborScope(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_audiencia_de_execucao_trabalhista"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_LABOR_SPLIT_WITHOUT_CAUSE),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "TRABALHISTA", "EXECUCAO")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "ELEITORAL",
                        "JUSTICA_ELEITORAL",
                        "ELEITORAL",
                        "COMUM",
                        "INSTRUCAO_ELEITORAL",
                        context.sectionVisible() && context.electoralScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.electoralScope(),
                        context.canSuggestSlot() && context.electoralScope(),
                        context.canOperationallySchedule() && context.electoralScope(),
                        context.canReschedule() && context.electoralScope(),
                        context.canCancel() && context.electoralScope(),
                        context.canReserveRoom() && context.electoralScope(),
                        context.canManageVirtualRoom() && context.electoralScope(),
                        context.canConfirmAttendance() && context.electoralScope(),
                        context.canRecordTerm() && context.electoralScope(),
                        context.canIssueHearingCommunications() && context.electoralScope(),
                        context.canPrepareHearingBundle() && context.electoralScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_em_calendario_eleitoral", "travar_pauta_por_periodo_oficial"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_ELECTORAL_SCHEDULING_OUTSIDE_CALENDAR),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "ELEITORAL", "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "ELEITORAL_COMUM",
                        "JUSTICA_ELEITORAL",
                        "ELEITORAL",
                        "COMUM",
                        "INSTRUCAO_CONTENCIOSA_ELEITORAL",
                        context.sectionVisible() && context.electoralScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.electoralScope(),
                        context.canSuggestSlot() && context.electoralScope(),
                        context.canOperationallySchedule() && context.electoralScope(),
                        context.canReschedule() && context.electoralScope(),
                        context.canCancel() && context.electoralScope(),
                        context.canReserveRoom() && context.electoralScope(),
                        context.canManageVirtualRoom() && context.electoralScope(),
                        context.canConfirmAttendance() && context.electoralScope(),
                        context.canRecordTerm() && context.electoralScope(),
                        context.canIssueHearingCommunications() && context.electoralScope(),
                        context.canPrepareHearingBundle() && context.electoralScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("controlar_audiencia_contenciosa_eleitoral"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_ELECTORAL_SCHEDULING_OUTSIDE_CALENDAR),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "ELEITORAL", "COMUM")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "ELEITORAL_ESPECIAL",
                        "JUSTICA_ELEITORAL",
                        "ELEITORAL",
                        "ESPECIAL",
                        "INSTRUCAO_DE_REGISTRO_OU_PRESTACAO_DE_CONTAS",
                        context.sectionVisible() && context.electoralScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.electoralScope(),
                        context.canSuggestSlot() && context.electoralScope(),
                        context.canOperationallySchedule() && context.electoralScope(),
                        context.canReschedule() && context.electoralScope(),
                        context.canCancel() && context.electoralScope(),
                        context.canReserveRoom() && context.electoralScope(),
                        context.canManageVirtualRoom() && context.electoralScope(),
                        context.canConfirmAttendance() && context.electoralScope(),
                        context.canRecordTerm() && context.electoralScope(),
                        context.canIssueHearingCommunications() && context.electoralScope(),
                        context.canPrepareHearingBundle() && context.electoralScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("tratar_pauta_de_registro_candidatura_ou_contas"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_ELECTORAL_SCHEDULING_OUTSIDE_CALENDAR),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "ELEITORAL", "ESPECIAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "MILITAR",
                        "JUSTICA_MILITAR",
                        context.militaryScope() && context.militaryFederalScope() ? "MILITAR_FEDERAL" : "MILITAR_ESTADUAL",
                        "COMUM",
                        "INSTRUCAO_OU_APRESENTACAO_MILITAR",
                        context.sectionVisible() && context.militaryScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.militaryScope(),
                        context.canSuggestSlot() && context.militaryScope(),
                        context.canOperationallySchedule() && context.militaryScope(),
                        context.canReschedule() && context.militaryScope(),
                        context.canCancel() && context.militaryScope(),
                        context.canReserveRoom() && context.militaryScope(),
                        context.canManageVirtualRoom() && context.militaryScope(),
                        context.canConfirmAttendance() && context.militaryScope(),
                        context.canRecordTerm() && context.militaryScope(),
                        context.canIssueHearingCommunications() && context.militaryScope(),
                        context.canPrepareHearingBundle() && context.militaryScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("respeitar_cadeia_de_comando_e_reserva_operacional"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_MILITARY_SCHEDULING_WITHOUT_CHAIN),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "MILITAR", context.militaryScope() && context.militaryFederalScope() ? "FEDERAL" : "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "MILITAR_ESTADUAL",
                        "JUSTICA_MILITAR_ESTADUAL",
                        "MILITAR_ESTADUAL",
                        "COMUM",
                        "INSTRUCAO_MILITAR_ESTADUAL",
                        context.sectionVisible() && context.militaryScope() && !context.militaryFederalScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canSuggestSlot() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canOperationallySchedule() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canReschedule() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canCancel() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canReserveRoom() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canManageVirtualRoom() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canConfirmAttendance() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canRecordTerm() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canIssueHearingCommunications() && context.militaryScope() && !context.militaryFederalScope(),
                        context.canPrepareHearingBundle() && context.militaryScope() && !context.militaryFederalScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("preservar_sigilo_organizacional_militar_estadual"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_MILITARY_SCHEDULING_WITHOUT_CHAIN),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "MILITAR", "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "MILITAR_FEDERAL",
                        "JUSTICA_MILITAR_FEDERAL",
                        "MILITAR_FEDERAL",
                        "COMUM",
                        "INSTRUCAO_MILITAR_FEDERAL",
                        context.sectionVisible() && context.militaryScope() && context.militaryFederalScope() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management()),
                        context.canRequestHearing() && context.militaryScope() && context.militaryFederalScope(),
                        context.canSuggestSlot() && context.militaryScope() && context.militaryFederalScope(),
                        context.canOperationallySchedule() && context.militaryScope() && context.militaryFederalScope(),
                        context.canReschedule() && context.militaryScope() && context.militaryFederalScope(),
                        context.canCancel() && context.militaryScope() && context.militaryFederalScope(),
                        context.canReserveRoom() && context.militaryScope() && context.militaryFederalScope(),
                        context.canManageVirtualRoom() && context.militaryScope() && context.militaryFederalScope(),
                        context.canConfirmAttendance() && context.militaryScope() && context.militaryFederalScope(),
                        context.canRecordTerm() && context.militaryScope() && context.militaryFederalScope(),
                        context.canIssueHearingCommunications() && context.militaryScope() && context.militaryFederalScope(),
                        context.canPrepareHearingBundle() && context.militaryScope() && context.militaryFederalScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("preservar_sigilo_organizacional_militar_federal"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_MILITARY_SCHEDULING_WITHOUT_CHAIN),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "MILITAR", "FEDERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "CONCILIACAO_MEDIACAO",
                        "AUTOCOMPOSICAO",
                        context.cejuscScope() ? "CEJUSC" : context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "AUTOCOMPOSICAO",
                        "AUTOCOMPOSICAO",
                        "CONCILIACAO",
                        context.sectionVisible() && (context.cejuscScope() || context.legalInstitution() || context.secretariat() || context.management()),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule() && (context.scheduler() || context.secretariat() || context.management()),
                        context.canReschedule() && (context.scheduler() || context.secretariat() || context.management()),
                        context.canCancel() && (context.scheduler() || context.secretariat() || context.management()),
                        context.canReserveRoom() && (context.scheduler() || context.secretariat() || context.management()),
                        context.canManageVirtualRoom() && (context.scheduler() || context.secretariat() || context.management()),
                        context.canConfirmAttendance(),
                        context.canRecordTerm() && (context.scheduler() || context.secretariat() || context.management()),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.scheduler() || context.secretariat() || context.management(),
                        context.requiresSecretariatCoordination() && !context.scheduler(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("controlar_convocacao_para_conciliacao_ou_mediacao", "gerir_pauta_de_cejusc"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "CONCILIACAO", context.cejuscScope() ? "CEJUSC" : "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "AUDIENCIAS_TELEPRESENCIAIS",
                        "TRANSVERSAL",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : context.laborScope() ? "TRABALHO" : context.electoralScope() ? "ELEITORAL" : context.militaryScope() ? "MILITAR" : "TRANSVERSAL",
                        "TELEPRESENCIAL",
                        "TELEPRESENCIAL",
                        context.sectionVisible() && (context.legalInstitution() || context.technicalSupport() || context.secretariat() || context.scheduler() || context.management() || context.prisonFlow()),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule() && (context.secretariat() || context.scheduler() || context.management()),
                        context.canReschedule() && (context.secretariat() || context.scheduler() || context.management()),
                        context.canCancel() && (context.secretariat() || context.scheduler() || context.management()),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm() && (context.secretariat() || context.scheduler() || context.management() || context.prisonFlow()),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        context.requiresSecretariatCoordination() || context.prisonFlow(),
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("validar_link_sala_telepresencial", "controlar_ambiente_reservado_de_depoimento"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "AUDIENCIA_TELEPRESENCIAL", "COMPETENCIA_DA_UNIDADE")));

        return List.copyOf(rites);
    }
}
