package com.tcc.pjb.backend.core.comunicacao.institucional.panel.application;

import com.tcc.pjb.backend.core.comunicacao.institucional.panel.domain.InstitutionalHearingRiteGovernance;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

class InstitutionalHearingPublicProtectionAndPenalRiteResolver {

    private final InstitutionalHearingRiteGovernanceFactory factory;

    InstitutionalHearingPublicProtectionAndPenalRiteResolver(InstitutionalHearingRiteGovernanceFactory factory) {
        this.factory = factory;
    }

    List<InstitutionalHearingRiteGovernance> resolve(InstitutionalHearingRiteGovernanceContext context) {
        ArrayList<InstitutionalHearingRiteGovernance> rites = new ArrayList<>();

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "FAZENDA_PUBLICA",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "FAZENDA",
                        "FAZENDA_PUBLICA",
                        "INSTRUCAO_OU_CONCILIACAO_COM_ENTE_PUBLICO",
                        context.publicTreasuryBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("validar_intervencao_da_fazenda_publica", "controlar_prazo_diferenciado_ente_publico"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "FAZENDA_PUBLICA", context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "FAZENDA_PUBLICA_ESTADUAL",
                        "JUSTICA_ESTADUAL",
                        "ESTADUAL",
                        "FAZENDA_PUBLICA",
                        "INSTRUCAO_OU_CONCILIACAO_COM_ENTE_PUBLICO_ESTADUAL",
                        context.publicTreasuryBroad() && context.broadCommonScope(),
                        context.canRequestHearing() && context.broadCommonScope(),
                        context.canSuggestSlot() && context.broadCommonScope(),
                        context.canOperationallySchedule() && context.broadCommonScope(),
                        context.canReschedule() && context.broadCommonScope(),
                        context.canCancel() && context.broadCommonScope(),
                        context.canReserveRoom() && context.broadCommonScope(),
                        context.canManageVirtualRoom() && context.broadCommonScope(),
                        context.canConfirmAttendance() && context.broadCommonScope(),
                        context.canRecordTerm() && context.broadCommonScope(),
                        context.canIssueHearingCommunications() && context.broadCommonScope(),
                        context.canPrepareHearingBundle() && context.broadCommonScope(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization() && context.broadCommonScope(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaminhar_para_procuradoria_estadual_ou_municipal"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "FAZENDA_PUBLICA", "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "FAZENDA_PUBLICA_FEDERAL",
                        "JUSTICA_FEDERAL",
                        "FEDERAL",
                        "FAZENDA_PUBLICA",
                        "INSTRUCAO_OU_CONCILIACAO_COM_ENTE_PUBLICO_FEDERAL",
                        context.publicTreasuryBroad() && context.federalScope(),
                        context.canRequestHearing() && context.federalScope(),
                        context.canSuggestSlot() && context.federalScope(),
                        context.canOperationallySchedule() && context.federalScope(),
                        context.canReschedule() && context.federalScope(),
                        context.canCancel() && context.federalScope(),
                        context.canReserveRoom() && context.federalScope(),
                        context.canManageVirtualRoom() && context.federalScope(),
                        context.canConfirmAttendance() && context.federalScope(),
                        context.canRecordTerm() && context.federalScope(),
                        context.canIssueHearingCommunications() && context.federalScope(),
                        context.canPrepareHearingBundle() && context.federalScope(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization() && context.federalScope(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaminhar_para_agu_ou_orgao_federal_representante"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "FAZENDA_PUBLICA", "FEDERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "EXECUCAO_FISCAL",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "FAZENDA",
                        "EXECUCAO_FISCAL",
                        "INSTRUCAO_EXCEPCIONAL_OU_CONCILIACAO_EXECUTIVA",
                        context.publicTreasuryBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_conciliacao_execucao_fiscal", "controlar_representacao_do_exequente_publico"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "EXECUCAO_FISCAL", context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "EXECUCAO_FISCAL_ESTADUAL",
                        "JUSTICA_ESTADUAL",
                        "ESTADUAL",
                        "EXECUCAO_FISCAL",
                        "CONCILIACAO_EXECUTIVA_ESTADUAL",
                        context.publicTreasuryBroad() && context.broadCommonScope(),
                        context.canRequestHearing() && context.broadCommonScope(),
                        context.canSuggestSlot() && context.broadCommonScope(),
                        context.canOperationallySchedule() && context.broadCommonScope(),
                        context.canReschedule() && context.broadCommonScope(),
                        context.canCancel() && context.broadCommonScope(),
                        context.canReserveRoom() && context.broadCommonScope(),
                        context.canManageVirtualRoom() && context.broadCommonScope(),
                        context.canConfirmAttendance() && context.broadCommonScope(),
                        context.canRecordTerm() && context.broadCommonScope(),
                        context.canIssueHearingCommunications() && context.broadCommonScope(),
                        context.canPrepareHearingBundle() && context.broadCommonScope(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization() && context.broadCommonScope(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("controlar_pauta_execucao_fiscal_estadual"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "EXECUCAO_FISCAL", "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "EXECUCAO_FISCAL_FEDERAL",
                        "JUSTICA_FEDERAL",
                        "FEDERAL",
                        "EXECUCAO_FISCAL",
                        "CONCILIACAO_EXECUTIVA_FEDERAL",
                        context.publicTreasuryBroad() && context.federalScope(),
                        context.canRequestHearing() && context.federalScope(),
                        context.canSuggestSlot() && context.federalScope(),
                        context.canOperationallySchedule() && context.federalScope(),
                        context.canReschedule() && context.federalScope(),
                        context.canCancel() && context.federalScope(),
                        context.canReserveRoom() && context.federalScope(),
                        context.canManageVirtualRoom() && context.federalScope(),
                        context.canConfirmAttendance() && context.federalScope(),
                        context.canRecordTerm() && context.federalScope(),
                        context.canIssueHearingCommunications() && context.federalScope(),
                        context.canPrepareHearingBundle() && context.federalScope(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization() && context.federalScope(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("controlar_pauta_execucao_fiscal_federal"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_TREASURY_AGREEMENT_WITHOUT_VALIDATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "EXECUCAO_FISCAL", "FEDERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "INFANCIA",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "INFANCIA",
                        "INFANCIA_E_JUVENTUDE",
                        "AUDIENCIA_COM_REDE_PROTETIVA",
                        context.childhoodBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("intimar_rede_protetiva_e_equipe_multidisciplinar", "preparar_fluxo_protegido"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_MINOR_EXPOSURE),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "INFANCIA", "PROTECAO")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "INFANCIA_PROTETIVA",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : "INFANCIA",
                        "INFANCIA_PROTETIVA",
                        "AUDIENCIA_COM_REDE_INTERDISCIPLINAR",
                        context.childhoodBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("intimar_mp_equipe_interdisciplinar", "reservar_fluxo_protetivo"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_MINOR_EXPOSURE),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "INFANCIA", "PROTETIVA")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "INFANCIA_INFRACIONAL",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : "INFANCIA",
                        "INFANCIA_INFRACIONAL",
                        "APRESENTACAO_OU_INSTRUCAO_INFRACIONAL",
                        context.childhoodBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        context.requiresJudicialAuthorization(),
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("controlar_sigilo_e_apresentacao_de_adolescente"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_PUBLIC_MINOR_EXPOSURE),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "INFANCIA", "INFRACIONAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "PENAL",
                        "JUSTICA_COMUM",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "PENAL",
                        "COMUM",
                        "INSTRUCAO_CRIMINAL",
                        context.penalBroad(),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule(),
                        context.canReschedule(),
                        context.canCancel(),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm(),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("intimar_mp_defesa_testemunhas", "controlar_sala_reservada_e_escolta_quando_necessario"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "PENAL", context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "GERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "PENAL_COMUM_ESTADUAL",
                        "JUSTICA_ESTADUAL",
                        "ESTADUAL",
                        "PENAL_COMUM",
                        "INSTRUCAO_CRIMINAL_ESTADUAL",
                        context.penalBroad() && context.broadCommonScope(),
                        context.canRequestHearing() && context.broadCommonScope(),
                        context.canSuggestSlot() && context.broadCommonScope(),
                        context.canOperationallySchedule() && context.broadCommonScope(),
                        context.canReschedule() && context.broadCommonScope(),
                        context.canCancel() && context.broadCommonScope(),
                        context.canReserveRoom() && context.broadCommonScope(),
                        context.canManageVirtualRoom() && context.broadCommonScope(),
                        context.canConfirmAttendance() && context.broadCommonScope(),
                        context.canRecordTerm() && context.broadCommonScope(),
                        context.canIssueHearingCommunications() && context.broadCommonScope(),
                        context.canPrepareHearingBundle() && context.broadCommonScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_em_pauta_criminal_estadual"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "PENAL", "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "PENAL_COMUM_FEDERAL",
                        "JUSTICA_FEDERAL",
                        "FEDERAL",
                        "PENAL_COMUM",
                        "INSTRUCAO_CRIMINAL_FEDERAL",
                        context.penalBroad() && context.federalScope(),
                        context.canRequestHearing() && context.federalScope(),
                        context.canSuggestSlot() && context.federalScope(),
                        context.canOperationallySchedule() && context.federalScope(),
                        context.canReschedule() && context.federalScope(),
                        context.canCancel() && context.federalScope(),
                        context.canReserveRoom() && context.federalScope(),
                        context.canManageVirtualRoom() && context.federalScope(),
                        context.canConfirmAttendance() && context.federalScope(),
                        context.canRecordTerm() && context.federalScope(),
                        context.canIssueHearingCommunications() && context.federalScope(),
                        context.canPrepareHearingBundle() && context.federalScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("encaixar_em_pauta_criminal_federal"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "PENAL", "FEDERAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "PENAL_TRIBUNAL_JURI",
                        "TRIBUNAL_DO_JURI",
                        context.broadCommonScope() ? "ESTADUAL" : "JURI",
                        "JURI",
                        "SESSAO_PLENARIA_OU_PREPARATORIA",
                        context.penalBroad() && context.broadCommonScope(),
                        context.canRequestHearing() && context.broadCommonScope(),
                        context.canSuggestSlot() && context.broadCommonScope(),
                        context.canOperationallySchedule() && context.broadCommonScope(),
                        context.canReschedule() && context.broadCommonScope(),
                        context.canCancel() && context.broadCommonScope(),
                        context.canReserveRoom() && context.broadCommonScope(),
                        context.canManageVirtualRoom() && context.broadCommonScope(),
                        context.canConfirmAttendance() && context.broadCommonScope(),
                        context.canRecordTerm() && context.broadCommonScope(),
                        context.canIssueHearingCommunications() && context.broadCommonScope(),
                        context.canPrepareHearingBundle() && context.broadCommonScope(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("organizar_sorteio_jurados_e_pauta_plenaria", "intimar_mp_dp_oab_para_atos_preparatorios"),
                        List.of(),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "JURI", "ESTADUAL")));

                factory.addIfRelevant(rites, factory.buildRite(
                        context.profile(),
                        context.workspace(),
                        context.schedulingScopeKey(),
                        "CUSTODIA",
                        "JUSTICA_PENAL",
                        context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "CUSTODIA",
                        "CUSTODIA",
                        "AUDIENCIA_DE_CUSTODIA",
                        context.sectionVisible() && (context.prisonFlow() || context.secretariat() || context.management() || context.legalInstitution() || context.technicalSupport() || context.scheduler()),
                        context.canRequestHearing(),
                        context.canSuggestSlot(),
                        context.canOperationallySchedule() && (context.secretariat() || context.scheduler() || context.management()),
                        context.canReschedule() && (context.secretariat() || context.scheduler() || context.management()),
                        context.canCancel() && (context.secretariat() || context.scheduler() || context.management()),
                        context.canReserveRoom(),
                        context.canManageVirtualRoom(),
                        context.canConfirmAttendance(),
                        context.canRecordTerm() && (context.secretariat() || context.scheduler() || context.management() || context.prisonFlow()),
                        context.canIssueHearingCommunications(),
                        context.canPrepareHearingBundle(),
                        context.requiresUnitIsolation(),
                        true,
                        true,
                        context.requestActors(),
                        context.preparatoryActors(),
                        context.communicationActors(),
                        context.operationalActors(),
                        context.trackingActors(),
                        context.oversightActors(),
                        List.of("confirmar_apresentacao_custodiado", "encaminhar_termo_unidade_prisional", "comunicar_juizo_processante_e_bnmp"),
                        List.of(InstitutionalHearingGovernanceMessages.NO_CUSTODY_WITHOUT_PRESENTATION),
                        factory.mergeSegregationGuards(context.topLevelSegregationGuards(), "CUSTODIA", context.broadCommonScope() ? "ESTADUAL" : context.federalScope() ? "FEDERAL" : "GERAL")));

        return List.copyOf(rites);
    }
}
