package com.tcc.pjb.backend.core.procedural;

public enum ProceduralAutomationCapability {
    AXIS_CLASSIFICATION,
    TPU_CLASS_SUGGESTION,
    COMPETENCE_SUGGESTION,
    TERRITORIAL_SNAPSHOT_ENRICHMENT,
    DOCUMENT_CHECKLIST_ENRICHMENT,
    SIGILO_SUGGESTION,
    ECONOMIC_SCREENING,
    RISK_SCORING,
    PRE_PROTOCOL_SCREENING,
    ROUTING_AUTOMATION,
    PROTOCOL_BLUEPRINT_PREPARATION,
    DISTRIBUTION_PRECHECK,
    INTERNAL_DISPATCH_HINTING,
    MANUAL_REVIEW_ESCALATION
}
