package com.tcc.pjb.backend.core.procedural;

public enum ProceduralAccelerationTrack {
    MARIA_DA_PENHA_PROTECAO_URGENTE,
    MARIA_DA_PENHA_REDE_PROTECAO,
    SAUDE_LEITO_UTI,
    SAUDE_SUPORTE_VITAL,
    SAUDE_FORNECIMENTO_ESSENCIAL,
    INFANCIA_PROTECAO_URGENTE,
    IDOSO_RISCO_ELEVADO,
    PRIORIDADE_VULNERABILIDADE,
    NENHUMA
}
