package com.tcc.pjb.backend.core.procedural;

public enum ProceduralAccelerationDirectiveCode {
    PRIORIDADE_ABSOLUTA_VIDA,
    DISTRIBUICAO_IMEDIATA,
    CONCLUSAO_IMEDIATA_MAGISTRADO,
    FORMULARIO_RISCO_OBRIGATORIO,
    SIGILO_REFORCADO_OFENDIDA,
    REDE_PROTECAO_ACIONAVEL,
    COMUNICACAO_AUTORIDADES_COMPETENTES,
    MONITORAMENTO_MEDIDA_PROTETIVA,
    TRIAGEM_SAUDE_CRITICA,
    NATJUS_CONSULTA_PRIORITARIA,
    REGULACAO_LEITO_VERIFICACAO,
    PROVA_CLINICA_MINIMA,
    LIMITACAO_AUTOMACAO_DECISORIA,
    FILA_ULTRAPRIORITARIA,
    REVISAO_HUMANA_OBRIGATORIA,
    BLOQUEIO_PUBLICACAO_AUTONOMA,
    ESCALONAMENTO_MULTICANAL,
    CONTROLE_PRAZO_LEGAL,
    PROTECAO_DADOS_SENSIVEIS,
    CHECKLIST_CUMPRIMENTO_URGENTE
}
