package com.tcc.pjb.backend.core.procedural;

public enum ProceduralExecutiveExplanationCode {
    AXIS_CONSENSUS_HIGH,
    AXIS_CONFLICT_REVIEW,
    AUTOMATION_SAFE_ROUTE,
    AUTOMATION_ASSISTED_ONLY,
    AUTOMATION_HUMAN_GATE,
    NATUREZA_JURIDICA_SIGNAL,
    SENSITIVE_DOMAIN_RESTRICTION,
    MISSING_FOUNDATIONAL_SIGNAL,
    QUALITY_LOW_DETERMINISM,
    QUALITY_STRONG_EVIDENCE,
    ARCHIVE_CONCEALMENT_RECOMMENDED,
    ARCHIVE_PARTY_GATE_REQUIRED,
    JUDICIAL_DRAFT_AGREEMENT_TEMPLATE,
    JUDICIAL_DRAFT_DESISTENCE_TEMPLATE
}
