package com.tcc.pjb.backend.core.kernel.recursal.mesh;

public enum RecursalClassFamily {
    CIVIL_CONHECIMENTO,
    CIVIL_EXECUCAO,
    CRIMINAL_ACAO,
    CRIMINAL_JURI,
    TRABALHISTA_CONHECIMENTO,
    TRABALHISTA_EXECUCAO,
    ELEITORAL_CONTENCIOSO,
    MILITAR_PENAL,
    TRIBUTARIO_FISCAL,
    FAZENDA_PUBLICA,
    PREVIDENCIARIO,
    FAMILIA_SUCESSOES,
    INFANCIA_JUVENTUDE,
    CONSTITUCIONAL,
    JUIZADO_ESPECIAL,
    EMPRESARIAL,
    ADMINISTRATIVO,
    AMBIENTAL,
    AGRARIO,
    INTERNACIONAL,
    OUTRA;

    public static final RecursalClassFamily CIVIL_ACAO = CIVIL_CONHECIMENTO;
}

