package com.tcc.pjb.backend.core.kernel.recursal.mesh;

public enum RecursalLifecycleState {
    RASCUNHO,
    INTERPOSTO,
    EM_SANEAMENTO_FORMAL,
    PREPARO_EM_COMPLEMENTACAO,
    PREPARO_CERTIFICADO,
    AGUARDANDO_CONTRARRAZOES,
    ADMISSIBILIDADE_ORIGEM,
    SOBRESTADO,
    SOBRESTADO_POR_PRECEDENTE,
    AGUARDANDO_APLICACAO_PRECEDENTE,
    PRECEDENTE_APLICADO,
    CASO_DISTINGUIDO,
    RETRATACAO,
    RETRATACAO_POR_PRECEDENTE,
    REMESSA_EM_CURSO,
    AUTOS_EM_TRANSITO,
    REMESSA_DEVOLVIDA,
    AUTUADO_NO_DESTINO,
    DISTRIBUIDO_NO_DESTINO,
    ADMISSIBILIDADE_DESTINO,
    SUSCITADO,
    AGUARDANDO_RESOLUCAO_CONFLITO,
    COMPETENCIA_DEFINIDA,
    RETORNO_AO_JUIZO_COMPETENTE,
    JULGAMENTO_MONOCRATICO,
    JULGAMENTO_COLEGIADO,
    PAUTA_SUSTENTACAO_DESIGNADA,
    SUSTENTACAO_REALIZADA,
    DILIGENCIA_DETERMINADA,
    INADMITIDO,
    DESERTO,
    INTEMPESTIVO,
    PROVIDO,
    PARCIALMENTE_PROVIDO,
    IMPROVIDO,
    NAO_CONHECIDO,
    ACOLHIDO,
    REJEITADO,
    PREJUDICADO,
    AGUARDANDO_REQUISICAO_PAGAMENTO_PUBLICO,
    AGUARDANDO_PRECATORIO,
    RPV_EXPEDIDA,
    PRECATORIO_EXPEDIDO,
    PAGAMENTO_PUBLICO_LIBERADO,
    BAIXADO,
    TRANSITADO_EM_JULGADO;

    public static final RecursalLifecycleState PROTOCOLADO = INTERPOSTO;

    public boolean finalState() {
        return switch (this) {
            case INADMITIDO, DESERTO, INTEMPESTIVO, PROVIDO, PARCIALMENTE_PROVIDO,
                    IMPROVIDO, NAO_CONHECIDO, ACOLHIDO, REJEITADO, PREJUDICADO,
                    BAIXADO, TRANSITADO_EM_JULGADO -> true;
            default -> false;
        };
    }
}
