apiVersion: v1
kind: LimitRange
metadata:
  name: pjb-defaults
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 512Mi
      default:
        cpu: "1"
        memory: 1Gi
      max:
        cpu: "8"
        memory: 8Gi
