apiVersion: v1
kind: ResourceQuota
metadata:
  name: pjb-quota
spec:
  hard:
    requests.cpu: "40"
    requests.memory: 80Gi
    limits.cpu: "80"
    limits.memory: 160Gi
    pods: "80"
    services: "20"
    secrets: "40"
    configmaps: "40"
