package com.tcc.pjb.backend.model.entity.enums;

public enum AtoCanonicoProcessual {
    ABRIR_VISTA_MP_INTERESSE_INCAPAZ,
    ABRIR_VISTA_MP_FISCAL_ORDEM_JURIDICA,
    ABRIR_VISTA_MP_ACAO_COLETIVA,
    ABRIR_VISTA_MP_FALENCIA_RECUPERACAO,
    INTIMAR_DEFENSORIA_CURADORIA_ESPECIAL,
    INTIMAR_DEFENSORIA_REU_SEM_ADVOGADO,
    INTIMAR_FAZENDA_PUBLICA_REPRESENTACAO,
    INTIMAR_FAZENDA_CITACAO_INICIAL,
    REQUISITAR_ESTUDO_PSICOSSOCIAL,
    REQUISITAR_ESTUDO_SOCIAL,
    COMUNICAR_CONSELHO_TUTELAR,
    ENCAMINHAR_CEJUSC,
    ENCAMINHAR_CEJUSC_MEDIACAO,
    NOMEAR_PERITO_E_ABRIR_ACEITE,
    NOMEAR_PERITO_E_FIXAR_QUESITOS,
    EXPEDIR_MANDADO_PRISAO,
    REQUISITAR_APRESENTACAO_REU_PRESO,
    REQUISITAR_REU_PRESO,
    COMUNICAR_UNIDADE_PRISIONAL_AUDIENCIA,
    EXPEDIR_OFICIO_CONTADORIA,
    EXPEDIR_OFICIO_CARTORIO,
    EXPEDIR_COOPERACAO_JUIZO,
    COMUNICAR_ORGAO_TECNICO_CONVENIADO,
    INTIMAR_ADVOCACIA_PUBLICA_REPRESENTACAO,
    TRAVAR_HOMOLOGACAO_ATE_VISTA_MP,
    NENHUM;

    public boolean bloqueiaMarcoProcessual() {
        return switch (this) {
            case ABRIR_VISTA_MP_INTERESSE_INCAPAZ,
                    ABRIR_VISTA_MP_FISCAL_ORDEM_JURIDICA,
                    ABRIR_VISTA_MP_ACAO_COLETIVA,
                    ABRIR_VISTA_MP_FALENCIA_RECUPERACAO,
                    INTIMAR_DEFENSORIA_CURADORIA_ESPECIAL,
                    INTIMAR_DEFENSORIA_REU_SEM_ADVOGADO,
                    REQUISITAR_ESTUDO_PSICOSSOCIAL,
                    REQUISITAR_ESTUDO_SOCIAL,
                    COMUNICAR_CONSELHO_TUTELAR,
                    ENCAMINHAR_CEJUSC_MEDIACAO,
                    NOMEAR_PERITO_E_ABRIR_ACEITE,
                    NOMEAR_PERITO_E_FIXAR_QUESITOS,
                    EXPEDIR_MANDADO_PRISAO,
                    REQUISITAR_APRESENTACAO_REU_PRESO,
                    REQUISITAR_REU_PRESO,
                    COMUNICAR_UNIDADE_PRISIONAL_AUDIENCIA,
                    EXPEDIR_OFICIO_CONTADORIA,
                    EXPEDIR_COOPERACAO_JUIZO,
                    COMUNICAR_ORGAO_TECNICO_CONVENIADO,
                    TRAVAR_HOMOLOGACAO_ATE_VISTA_MP -> true;
            default -> false;
        };
    }

    public String gateCode() {
        return switch (this) {
            case ABRIR_VISTA_MP_INTERESSE_INCAPAZ -> "GATE_MP_INTERESSE_INCAPAZ";
            case ABRIR_VISTA_MP_FISCAL_ORDEM_JURIDICA -> "GATE_MP_VISTA_PENDENTE";
            case ABRIR_VISTA_MP_ACAO_COLETIVA -> "GATE_MP_ACAO_COLETIVA";
            case ABRIR_VISTA_MP_FALENCIA_RECUPERACAO -> "GATE_MP_FALENCIA_RECUPERACAO";
            case INTIMAR_DEFENSORIA_CURADORIA_ESPECIAL, INTIMAR_DEFENSORIA_REU_SEM_ADVOGADO -> "GATE_DEFENSORIA_CURADORIA_ESPECIAL";
            case REQUISITAR_ESTUDO_PSICOSSOCIAL, REQUISITAR_ESTUDO_SOCIAL -> "GATE_ESTUDO_PSICOSSOCIAL";
            case COMUNICAR_CONSELHO_TUTELAR -> "GATE_CONSELHO_TUTELAR";
            case ENCAMINHAR_CEJUSC_MEDIACAO -> "GATE_CEJUSC_MEDIACAO";
            case NOMEAR_PERITO_E_ABRIR_ACEITE, NOMEAR_PERITO_E_FIXAR_QUESITOS -> "GATE_PERITO_ACEITE";
            case EXPEDIR_MANDADO_PRISAO, REQUISITAR_APRESENTACAO_REU_PRESO, REQUISITAR_REU_PRESO -> "GATE_APRESENTACAO_REU_PRESO";
            case COMUNICAR_UNIDADE_PRISIONAL_AUDIENCIA -> "GATE_UNIDADE_PRISIONAL_AUDIENCIA";
            case EXPEDIR_OFICIO_CONTADORIA -> "GATE_CONTADORIA";
            case EXPEDIR_COOPERACAO_JUIZO -> "GATE_COOPERACAO_JUDICIAL";
            case COMUNICAR_ORGAO_TECNICO_CONVENIADO -> "GATE_ORGAO_TECNICO";
            case TRAVAR_HOMOLOGACAO_ATE_VISTA_MP -> "GATE_MP_VISTA_PENDENTE";
            default -> null;
        };
    }
}
