package com.tcc.pjb.backend.model.entity.enums;

public enum InstitutionalSecurityFactor {
    LOGIN_GOVBR,
    LOGIN_INSTITUCIONAL_GERENCIADO,
    GOVBR_PRATA_OURO,
    MFA_ATIVO,
    CERTIFICADO_ICP_BRASIL,
    NOMEACAO_ATIVA,
    AFILIACAO_HOMOLOGADA,
    REDE_INSTITUCIONAL_CONFIAVEL,
    AUTORIZACAO_REMOTA_CERTIFICADO,
    DISPOSITIVO_HOMOLOGADO
}
