package com.tcc.pjb.backend.model.entity.enums;

public enum OrganizacaoExtraJudicialKind {
    MINISTERIO_PUBLICO,
    DEFENSORIA_PUBLICA,
    ADVOCACIA_PUBLICA,
    FAZENDA_PUBLICA,
    SEGURANCA_PUBLICA,
    POLICIA_PENAL,
    ADMINISTRACAO_PRISIONAL,
    PROTECAO_INFANTOJUVENIL,
    APOIO_TECNICO_JUDICIAL,
    AUTOCOMPOSICAO,
    CARTORIO_EXTRAJUDICIAL,
    COOPERACAO_JUDICIAL_EXTERNA,
    ORGAO_TECNICO_CONVENIADO,
    OUTRO;

    public static OrganizacaoExtraJudicialKind fromDestinatario(DestinatarioInstitucionalKind destinatarioKind) {
        if (destinatarioKind == null) {
            return OUTRO;
        }
        return switch (destinatarioKind) {
            case MINISTERIO_PUBLICO -> MINISTERIO_PUBLICO;
            case DEFENSORIA_PUBLICA -> DEFENSORIA_PUBLICA;
            case ADVOCACIA_PUBLICA, PROCURADORIA_ESTADO, PROCURADORIA_MUNICIPIO, AGU -> ADVOCACIA_PUBLICA;
            case FAZENDA_PUBLICA -> FAZENDA_PUBLICA;
            case DELEGACIA_POLICIA, DELEGACIA_POLICIA_CIVIL, DELEGACIA_POLICIA_FEDERAL -> SEGURANCA_PUBLICA;
            case POLICIA_PENAL -> POLICIA_PENAL;
            case UNIDADE_PRISIONAL -> ADMINISTRACAO_PRISIONAL;
            case CONSELHO_TUTELAR -> PROTECAO_INFANTOJUVENIL;
            case PERICIA_JUDICIAL, PERITO_JUDICIAL, CONTADORIA_JUDICIAL, EQUIPE_PSICOSSOCIAL, ASSISTENTE_SOCIAL_JUDICIAL -> APOIO_TECNICO_JUDICIAL;
            case CEJUSC -> AUTOCOMPOSICAO;
            case CARTORIO_EXTRAJUDICIAL -> CARTORIO_EXTRAJUDICIAL;
            case JUIZO_DEPRECADO, ORGAO_JUDICIAL_EXTERNO -> COOPERACAO_JUDICIAL_EXTERNA;
            case ORGAO_TECNICO_CONVENIADO -> ORGAO_TECNICO_CONVENIADO;
        };
    }
}
