package com.tcc.pjb.backend.model.entity.enums;


public enum ResultadoValidacaoAudiencia {

    

    VALIDA_CONSTITUCIONALMENTE,
    VALIDA_LEGALMENTE,
    VALIDA_REGIMENTALMENTE,

    

    VALIDA_COM_RESTRICOES_LEGAIS,
    VALIDA_COM_RESTRICOES_REGIMENTAIS,
    VALIDA_COM_LIMITACAO_DE_COMPETENCIA,
    VALIDA_SEM_EFEITO_DECISORIO,
    VALIDA_APENAS_PARA_INSTRUCAO,

    

    INCOMPATIVEL_COM_O_RITO,
    INCOMPATIVEL_COM_A_FASE_PROCESSUAL,
    INCOMPATIVEL_COM_O_MODULO_PROCESSUAL,
    INCOMPATIVEL_COM_A_MODALIDADE_DE_AUDIENCIA,
    INCOMPATIVEL_COM_O_MEIO_DE_REALIZACAO,

    

    VEDADA_PELA_CONSTITUICAO,
    VEDADA_POR_LEI_PROCESSUAL,
    VEDADA_POR_LEI_ESPECIAL,
    VEDADA_POR_REGIMENTO_INTERNO,

    

    NAO_ADMITIDA_NO_STF,
    NAO_ADMITIDA_EM_TRIBUNAL_SUPERIOR,
    NAO_ADMITIDA_EM_JUIZADO_ESPECIAL,
    NAO_ADMITIDA_EM_ORGAO_COLEGIADO,

    

    ATO_INEXISTENTE_JURIDICAMENTE,
    ATO_NULO_ABSOLUTAMENTE,
    ATO_ANULAVEL,

    

    CONFIGURACAO_PROCESSUAL_INCONSISTENTE,
    AUSENCIA_DE_PREVISAO_LEGAL,
    CASO_NAO_MAPEADO,

}
