package com.tcc.pjb.backend.model.entity.enums;

public enum TipoInstituicao {
    TRIBUNAL,
    MINISTERIO_PUBLICO,
    DEFENSORIA_PUBLICA,
    ADVOCACIA_PUBLICA,
    PROCURADORIA_ESTADO,
    PROCURADORIA_MUNICIPIO,
    AGU,
    FAZENDA_PUBLICA,
    DELEGACIA_POLICIA,
    POLICIA_PENAL,
    UNIDADE_PRISIONAL,
    CONSELHO_TUTELAR,
    CARTORIO_EXTRAJUDICIAL,
    ORGAO_PERICIAL,
    CEJUSC,
    CENTRAL_MANDADOS,
    OUTRO
}
